### ISSUE TITLE
Cant open tooltip from code

### ISSUE THREAD

**Issue by Diskyp** [StephanWagner/jBox#101]
Heyllo!
Maybe problem on my side but i cant get whats wrong.
Im just create one simple tooltip and want that to immidiatly open:
```
i.jBox('Tooltip',{
    content:'Maximum of  '+m[1]+' symbols allowed!'
}).open()
```
(var i here is an jquery object for sure)
And nothing happend. No tooltip and also no errors in console. Tooltip still appear on hover but ignore `.open()` method. Im tryed to open tooltip with timeout but the same happend.
Am i doing something wrong or what?

**Comment by StephanWagner** [comment]
Hi Diskyp,
jBox doesn't work on elements, you need to initialise an instance of jBox and set the target to the element where you'd like it to open: https://jsfiddle.net/StephanWagner/1regLqqz/
