### ISSUE TITLE
Sound not working on mobile device

### ISSUE THREAD

**Issue by baeeunmang** [StephanWagner/jBox#102]
&lt;a id="Notice-1"&gt;Click me&lt;/a&gt;

&lt;script&gt;
$(document).ready(function() {
	setTimeout(function () {
		new jBox('Notice', {
			audio: '../../Jsource/audio/bling1',
			volume: 80,
			color: 'black',
			content: 'text'
		});		
	}, 200);

	$('#Notice-1').click(function() {		
		new jBox('Notice', {
			audio: '../../Jsource/audio/bling1',
			volume: 80,
			color: 'black',
			content: 'text'
		});		
	});
});
&lt;/script&gt;

If you click the link, you will hear sound on your PC or mobile.
However, setTimeout does not sound on mobile devices.
The same is true for functions other than click events.

**Comment by StephanWagner** [comment]
Seems to be a restriction on mobile devices. They seem not to play sound if it's not triggered by click, check out this fiddle on a mobile device, only the manually opened notice will play sound: https://jsfiddle.net/zsqg3Loh/

**Comment by baeeunmang** [comment]
Thank you for your quick and kind answers.
