### ISSUE TITLE
Illegal return statement

### ISSUE THREAD

**Issue by kirin-yuen** [StephanWagner/jBox#105]
Hi, I found an error when run following code(all files have been emmbed to html).

I need to submit form via this button after popup jbox confirm and press ok, but after pressing ok exactlly output `Illegal return statement` on the console, Is that a bug? Thanks for help in advance.

```
‘html’
<form runat="server" id="form1">
    <button type="submit" onclick="return true" data-confirm="r u confirm">Submit</button>
</form>

<script>
    window.onload = function(){
        new jBox('Confirm', {});
    }
</script>
```

Following Error :
```
VM11651:1 Uncaught SyntaxError: Illegal return statement
    at s.<anonymous> (jBox.Confirm.min.js:1)
    at HTMLDivElement.dispatch (jquery.min.js:5)
    at HTMLDivElement.v.handle (jquery.min.js:5)
(anonymous) @ jBox.Confirm.min.js:1
dispatch @ jquery.min.js:5
v.handle @ jquery.min.js:5
```

**Comment by StephanWagner** [comment]
Hi kirin-yuen,

You can create a function that handles your confirm logic and set this function to the onclick event:
https://jsfiddle.net/StephanWagner/3oczLxtp/

```
<form runat="server" id="form1">
    <button type="submit" onclick="submitConfirm()" data-confirm="r u confirm">Submit</button>
</form>
```

```
function submitConfirm() {
	console.log('Confirmed');
	return true;
}
```
Cheers,
Stephan

**Comment by kirin-yuen** [comment]
Yes, I try this before, but it won't submit form after confirm, and I add the action to a.php to see that result fork jsfiddle as following links.
[https://jsfiddle.net/j1vg0L4c/](https://jsfiddle.net/j1vg0L4c/)

**Comment by StephanWagner** [comment]
Hi, you need to attach the jBox confirm to the button. By default jBox Confirm attaches itself to elements with the attribute ```data-confirm``` but you can overwrite this with the method ```attach```. See this fiddle: https://jsfiddle.net/StephanWagner/0wocvby2/

```
<button class="confirm-button" type="submit" onclick="submitConfirm()">Will be Submit</button>

new jBox('Confirm', {
  	attach: '.confirm-button'
  });
```

**Comment by kirin-yuen** [comment]
Yes, this way I have try too, submit the form is ok.

 But our server side language is webform .net, and there are many submit buttons in a form, these buttons are all the component of webform, no formaction attrubute otherwise I would like follow [HTML forms with multiple submit buttons](https://makandracards.com/makandra/54158-html-forms-with-multiple-submit-buttons).

So I have to ask for your help here.

**Comment by StephanWagner** [comment]
You could also just attach the jBox to all submit buttons within the form and then overwrite the default submit action of jBox Confirm: https://jsfiddle.net/StephanWagner/0wocvby2/2/

````
new jBox('Confirm', {
  attach: 'form button[type="submit"]',
  confirm: function () {
    $('form').submit();
  }
});```

**Comment by kirin-yuen** [comment]
Thanks for your help, appreciate a lot.
