### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by astegmaier** [StephanWagner/jBox#111]
First, I wanted to say 'thank you' for contributing such a great library - I've been using it in one of my projects, and it works great!

My project uses typescript, and I went ahead and wrote a complete typescript declaration file for `jBox` based off the documentation. I was wondering if you'd be open to including it in the main package?

(The other option is for me to contribute it to `DefinitelyTyped`, but if you're okay with keeping it here, it makes it easier for TypeScript users to acquire and stay in sync with any changes between versions).

Just in case you think it's a good idea, I created PR #112 for you to review.

**Comment by StephanWagner** [comment]
Hey @astegmaier,

thanks a lot, thats a great addition! I've added 2 options that are quite new to jBox: https://github.com/StephanWagner/jBox/commit/c0e754776635d31b74c448b65cdb1569d64a020c

Also, what's your thoughts on moving the jBox.d.ts into the src dir? Maybe also into /src/js or maybe /src/ts? I'm not sure what's best practice here?

**Comment by astegmaier** [comment]
I think for people who are importing the files into their typescript project through webpack and `require` statements (like me), you can put the d.ts file wherever you like as long as the `package.json` points to it. I've seen people do different things in different projects, so it's up to you - maybe putting it in `src` right next to `jBox.js` would make it clearer.

Also, I'm not as familiar with it but I _think_ if the d.ts file ends up with the same name as the javascript file in the `dist` directory that non-typescript projects are importing, then some code editors like VSCode`will be able to light up IntelliSense, which would provide goodness for regular javascript projects too. If you wanted to go down that route, maybe moving the main d.ts file to the `src` directory, and adding a build step to copy it into the `dist` directory would make sense?

**Comment by astegmaier** [comment]
Also, I found a small bug in the original PR that I wanted to fix - see #113

**Comment by StephanWagner** [comment]
Thanks! I've moved it into `src/js/`, I too think that might make the most sense. I'll be looking into creating a build version for it too. I'll leave that issue open for now until I get around to to that.

I just released a new version with these changes in it: https://github.com/StephanWagner/jBox/releases/tag/v0.5.4

Thanks again, really appreciate the help!
