### ISSUE TITLE
Logo creation

### ISSUE THREAD

**Issue by jorlogicus** [StephanWagner/jBox#114]
Hello @StephanWagner today while exploring GitHub looking for interesting projects found yours and I would love to contribute by designing a logo for it. I'm a designer under construction and an open source enthusiast. The idea is that we work through the process together so I will be sending sketches and we you will tell me what to add, modify, etc. Of course it's totally free and you can quit whenever you want. In case you agree, please let me know any preferences you may have about colors, shapes, etc. So I have something to start with.

Kind regards.

**Comment by StephanWagner** [comment]
Hi @jorlogicus,
right now there is no need for a logo. And if jBox will get a logo in the future, I'd probably design it myself. Logo creation is fun :) Thanks for the offer though!
