### ISSUE TITLE
Closing modal window on mobile

### ISSUE THREAD

**Issue by coax** [StephanWagner/jBox#116]
Using (latest) version 0.5.4

When you tap on Close in modal window on mobile device (even in mobile emulator in Developer Tools on desktop), it touches the background element as well, so if modal is opened over links, when you tap close it will init the link below the modal.

![ezgif com-resize](https://user-images.githubusercontent.com/189817/52011885-7753e200-24d9-11e9-96e3-b90e04c8f85f.gif)

**Comment by StephanWagner** [comment]
Hi @coax, very strange, I couldn't reproduce the issue. Could you send some code. How did you attach the element to the link?

**Comment by coax** [comment]
You know what? Immediately after I read what you replied (tnx for the fast reply btw) I checked my code and seen `fade: 0`, thinking I should try to disable that (tried everything else) and the issue is gone.

The original code which was making problem with close:
```
var orders = new jBox('Modal', {
		preventDefault: true,
		attach: '.menu a',
		fade: 0,
		blockScroll: true,
		fixed: true,
		closeButton: 'box',
		animation: { open: 'slide:top', close: 'slide:top' },
		...
```
