### ISSUE TITLE
Modal position is bugged until resize (on Firefox!)

### ISSUE THREAD

**Issue by Momentanius** [StephanWagner/jBox#117]
Greetings! First things first, great work on the plugin! Very useful.

So, I've been using it to display some PDF's on my company's website. On Google Chrome, it works flawlessly:
![image](https://user-images.githubusercontent.com/4644408/53190876-4a32b500-35e9-11e9-914c-5bfde88306ce.png)

But, unfortunately, I can't say the same for Firefox - The position is way off, and the code is exactly the same!

![image](https://user-images.githubusercontent.com/4644408/53190983-7b12ea00-35e9-11e9-8bbc-ec8a6f0501df.png)

I've searched around for a bit in the issues tab but got no good solution. I've tried using `ConstructOnInit: true`, or setting the width and height with `onCreated `and `onOpen`, to no success.

Here is the code that creates the Jbox:

```
    function createStampModal(uri) {
        var width = $(window).width() - $(window).width() * 0.1;
        var height = $(window).height() - $(window).height() * 0.1;
        var content = '<embed src="{0}" width="' + width + '" height="' + height + '"></embed>';
        content = content.replace('{0}', createDocumentUrl(uri));

        new jBox('Modal', {
            attach: '#buttonViewStamp',
            content: content
        });
    }
```

Thanks for the help! Hopefully we can find a fix together.

**Comment by StephanWagner** [comment]
Hi @Momentanius,

what version are you using?

I can't reproduce the issue. Tested in Chrome, Firefox on Mac and Windows. See this fiddle: https://jsfiddle.net/StephanWagner/72L0rm5e/

Also, I just released version v0.5.5 which fixes a bug that positioned the jBox above the close button in the overlay. Could you try with the newest version? If the issue persists, can you send me a link or a fiddle where I can reproduce the issue? 

Cheers,
Stephan
