### ISSUE TITLE
el.css is not a function on Notice

### ISSUE THREAD

**Issue by gunarecro** [StephanWagner/jBox#119]
Hi Stephan 

`<script>
		jQuery(document).ready(function() {
			new jBox('Confirm', {
				confirmButton: 'Do it!',
				cancelButton: 'Nope'
			});
		});

		function doit() {
			new jBox('Notice', {content: 'Yay! You did it!', color: 'green', attributes: {y: 'bottom'}});
		}
		</script>` 
		`<div data-confirm="Do you really want to do this?" onclick="doit()" >Click me!</div>
		<a href="https://stephanwagner.me" data-confirm="Do you really want to leave this page?">Click me!</a>`

This is the code i'm using.

I'm facing issue mentioned below it is happening whenever i click on Do it  button on modal.
Please help me to rectify this issue.

using Chrome browser (73 version) on windows 10

**jQuery v1.11.3**
**Issue**:

`jBox.Notice.js:155 Uncaught TypeError: el.css is not a function
    at jBox._onPosition (jBox.Notice.js:155)
    at jBox._fireEvent (jBox.js:368)
    at jBox.position (jBox.js:1566)
    at jBox.<anonymous> (jBox.js:1628)
    at jBox.open (jBox.js:1697)
    at jBox._onInit (jBox.Notice.js:88)
    at jBox._fireEvent (jBox.js:368)
    at new jBox (jBox.js:1016)
    at doit (dashboard:716)
    at eval (eval at <anonymous> (jBox.Confirm.js:69), <anonymous>:1:1)`

Thanks,
Guna.

**Comment by gunarecro** [comment]
Hi Stephan,

In **jsfiddle** all the components have been working fine but whenever i use **Notice** component that time only i'm getting el.css is not a function 

I'm also using jBox.all.min.css and jBox.all.min.js these two libraries only

Thank you,
Guna.

**Comment by StephanWagnerFielmann** [comment]
The error seems to come from jBox.Notice.js. Not sure why though. I just tried the fiddle with jQuery 1.9.1 and it did work. Could you provide a fiddle or some code which reproduces the error?

**Comment by StephanWagner** [comment]
The error seems to come from jBox.Notice.js. Not sure why though. I just tried the fiddle with jQuery 1.9.1 and it did work. Could you provide a fiddle or some code which reproduces the error?

**Comment by gunarecro** [comment]
I hope you find my details in mail.

**Comment by duanluan** [comment]
> The error seems to come from jBox.Notice.js. Not sure why though. I just tried the fiddle with jQuery 1.9.1 and it did work. Could you provide a fiddle or some code which reproduces the error?

改下源码，这样就可以用 1.9.1 了 `el = $(stacks[pos][i]);`

**Comment by wobility** [comment]
Hi,

I have same problem do you find where the problem come from ?

**Comment by StephanWagner** [comment]
It seams that your jQuery Version is outdated. The fiddle still works with newest jBox and jQuery version 3.4.1: https://jsfiddle.net/StephanWagner/raqnhLef/3/

Could you try with newer jQuery Verison.

**Comment by StephanWagner** [comment]
Actually, after some more testing I could reproduce the error. Please test with jBox version 1.2.2. I just released it.
