### ISSUE TITLE
can't enter data

### ISSUE THREAD

**Issue by Grandpa-G** [StephanWagner/jBox#122]
When the jbox comes up, I am not able to mouse click into any input fields. I can tab into the fields and enter data. here is my definition:
` newModal = new jBox('Modal', {
    title: 'New Batch',
    overlay: false,
    createOnInit: true,
    draggable: true,
    repositionOnOpen: false,
    repositionOnContent: false,
    isolateScroll: true,
    theme: 'TooltipBorder',
  onClose: function() {closeNewBatch();},
 content: $('#newFormula')
  });
`
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
`
`<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.1/dist/jBox.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.1/dist/jBox.all.min.css" rel="stylesheet">
`

Apparently, if you make the box draggable, then it can't be edited with the mouse. Any way around that?

**Comment by StephanWagnerFielmann** [comment]
Hey @Grandpa-G, 
yeah, it seams that the draggable option overrides the click event, so it can't focus the textfield.

You could set the option draggable to 'title': `dragabble: 'title'`

This way you can still drag the box around by clicking the title element, and you also can click into element in the content area. See this fiddle: https://jsfiddle.net/StephanWagner/Lbp4qtuo/

**Comment by StephanWagner** [comment]
Hey @Grandpa-G,
yeah, it seams that the draggable option overrides the click event, so it can't focus the textfield.

You could set the option draggable to 'title': `dragabble: 'title'`

This way you can still drag the box around by clicking the title element, and you also can click into element in the content area. See this fiddle: https://jsfiddle.net/StephanWagner/Lbp4qtuo/

**Comment by Grandpa-G** [comment]
Seems to work perfectly. Is this documented? If not, might be a good idea. Took me a long time to get the cause/relationship.
Thanks.

**Comment by StephanWagner** [comment]
It‘s only documented that the option draggable: title exists, not that this could cause this issue though. Might add it to the documentation for next version.
