### ISSUE TITLE
Minor fix for Demo.css

### ISSUE THREAD

**Issue by ghaecker** [StephanWagner/jBox#123]
Hi Stephan,

Nothing urgent - just a little fix sometime when you're already in the code.

While catching up with all your recent changes (thanks for those), I noticed a minor .css error that I fixed in my fork some time ago, but is still in your repository.  There's a ';;' at the end of a line.  I know - it's earth-shattering, right?  It gets worse: according to `git blame`, it's my bad.  :)  (Sorry about that.)

I tried attaching a diff file, but GitHub doesn't like that.  It's hardly worth a pull request or even a separate commit on your part.  So... I'll paste the little diff in here.

```text
diff --git a/Demo/Demo.css b/Demo/Demo.css
index 70192c8..88ae23d 100644
--- a/Demo/Demo.css
+++ b/Demo/Demo.css
@@ -727,16 +727,14 @@ button::-moz-focus-inner {
   background-color: rgba(0, 0, 0, .35);
 }
 
-.jBox-content p {
+.jBox-content p, #hold-position .jBox-content div.inp {
     margin-top: 0.5em;
 }
 
 #hold-position .jBox-title {
   white-space: nowrap;
 }
-#hold-position .jBox-content div.inp {
-  margin-top: 0.5em;;
-}
+
 #hold-position .jBox-content .norm {
   width: 270px;
   height: auto;
```

Will that work for you?

Hm... let me try adding it as a .txt file, since that's all it is anyway.  Hey - looks like that worked!

[Demo.css.diff.txt](https://github.com/StephanWagner/jBox/files/3159609/Demo.css.diff.txt)

**Comment by StephanWagner** [comment]
Hey @ghaecker,

thanks for the info. I took this opportunity to refactor the demos and fix some minor bugs on the way. I just released v0.8.1 with those changes. You'll notice that the advanced draggable modal demos are now in the playground area called inception.

Cheers, 
Stephan
