### ISSUE TITLE
blockScroll with blockScrollAdjust

### ISSUE THREAD

**Issue by ghaecker** [StephanWagner/jBox#124]
Is is just me, or is there an issue with blockScrollAdjust?  In a Modal with blockScroll set to true and letting the default blockScrollAdjust (true) prevail, scrolling isn't blocked.  I see this issue in the demo with the first Modal.  It says, "Try to scroll ...it's blocked", but it isn't blocked at all.  The only way I got it to block was by setting blockScrollAdjust to false.  Maybe I don't understand how to use or set blockScrollAdjust.

**Comment by StephanWagner** [comment]
On what OS and browser are you testing?
Just tested with Chrome and Firefox on Windows and macOS. Both seem to work.

**Comment by ghaecker** [comment]
macOS Mojave 10.14.4 (18E226)
* Safari 12.1 (14607.1.40.1.4)
* Firefox Quantum 66.0.5
* Chrome 74.0.3729.131 (Official Build)

Hm... the only one it isn't working on is Safari.  I could have sworn it failed in Firefox yesterday - and maybe it did, because I loaded a new version today.  I didn't try Chrome before.

**Comment by StephanWagner** [comment]
I could reproduce the issue with Safari.
jBox blocks scrolling with `overflow-y: hidden`. It seems Safari needs `overflow: hidden` though.
I'll see that I get around to fix that soon.

**Comment by ghaecker** [comment]
No rush.  Thanks for checking it.

**Comment by StephanWagner** [comment]
Fixed now with version 1.0.0
