### ISSUE TITLE
Great product but a little problem with the namefiles

### ISSUE THREAD

**Issue by ktryndchrs** [StephanWagner/jBox#125]
I am using bower to fetch jBox on my website. However, the filename needs to be renamed because the server doesn't handle uppercase. This is not ideal since if we make an update, this may break everything... so my decision, for now, his to to simply extract you (great) plugin from bower and rename it locally. Probably I am not the only one with this issue.

Thank you

**Comment by StephanWagner** [comment]
This is indeed a problem. When I started with jBox I didn't even know about bower, npm, etc. I guess thats why it never occurred to me. Can you send me a bower file and maybe some code to replicate your issue. I'll try to find out some more about it and how to best solve it. I'm worried that when I  just release a new 1.1.0 version with the js and css files renamed that it'll cause lot's of other updates to fail.

Any suggestions appreciated.

**Comment by StephanWagner** [comment]
`bower install jbox` works fine. Therefore closing this issue.
I issue still exists, feel free to reopen and provide some instructions of how I could to reproduce the issue.
