### ISSUE TITLE
Stacking notices at the bottom not working

### ISSUE THREAD

**Issue by mbaas2** [StephanWagner/jBox#126]
I'm trying to stack notices at the bottom. This has worked in earlier versions, but somehow stopped.
See [this fiddle](https://jsfiddle.net/mbaas/hoqumrnf/3/) for a repro.

**Comment by StephanWagner** [comment]
Actually notices work a bit different with positioning. You have to use the option`attributes` to tell where they should appear. And then use `position` for the offset. See this fiddle: https://jsfiddle.net/StephanWagner/m71bpfdw/1/

This is indeed confusing and I never liked it this way too much. You can leave this issue open and I'll see if I find time to get around to support the option position for notices too.

**Comment by StephanWagner** [comment]
Leaving the options as they are, not to add any more confusion.
