### ISSUE TITLE
Suggestion for Improving Events

### ISSUE THREAD

**Issue by Nuadire** [StephanWagner/jBox#128]
At the moment there is no possibility to cancel the action on the events stage.

I suggest adding to events: return (boolean).
If false is returned, the action is canceled.

**Comment by StephanWagner** [comment]
Which events do you mean exactly, or what is the use case? I can't think of an event that could be cancelable.

The ajax calls can be canceled with the method `.cancelAjax()`.

**Comment by Nuadire** [comment]
I am interested in canceling the closing window.
When the user presses [esc] or [x]. I want to show a message to the user and ask: Do you want to save intermediate data? (with Yes / No / Cancel buttons)
“Cancel” - the window is not closed and the user has the opportunity to continue working.

**Comment by Nuadire** [comment]
Or when you press [esc] or [x], a message appears: the required fields are not filled. And the window does not close.

**Comment by StephanWagner** [comment]
I see. So you need to get a bit creative then. You can manage closing jBoxes with several options: https://stephanwagner.me/jBox/options#closing-jbox

In this fiddle for example, I disabled the default closing options [esc] and when you click on the overlay. Then I overwrite the click event on the close button with my own function which will open a confirm modal. This confirm modal then closes itself and the other modal when you click confirm:
https://jsfiddle.net/StephanWagner/cvmntbod/

You can now add other requirements for closing the modal, like that there needs to a filled textfield. You could also use tooltips. See this fiddle:
https://jsfiddle.net/StephanWagner/cvmntbod/6/

And when you want to check for closing when you press [esc], just add an event listener for esc:
https://jsfiddle.net/StephanWagner/cvmntbod/11/

Is that something you were after?

**Comment by StephanWagner** [comment]
Seems to be fixed with my last answer. If not, feel free to reopen and elaborate what your after.
