### ISSUE TITLE
Open jbox tooltip near(at the bottom) of the cursor.

### ISSUE THREAD

**Issue by BoumBam** [StephanWagner/jBox#129]
I want to show the result of what user is writing now in a tooltip.
when the result is shown in the tooltip, the user can choose the shown result in the tooltip.
How could I show tooltip where the cursor is ?
How could I attach the tooltip to the cursor ?

I'm using that script to show tooltip:
```
var  tag_system_result =  new jBox('Tooltip', { 
                attach: '.show_tag_system_result',
                width: 300,
                theme: 'TooltipBorderThick',
                adjustTracker: true,
                adjustPosition: true,
               // trigger: 'click',
                pointer: false, 
                closeOnClick: 'body',
                closeOnEsc: true,
                position: {
                  x: 'center',
                  y: 'top'
                },
                offset: {
                  y: -10
                },
                autoClose: 10000,
                animation: 'zoomIn',
                content: $('#tag_system_result_container')
        });

```

I can't use  new jBox('Mouse', {}) because with that user can't click on tooltip.

**Comment by StephanWagner** [comment]
I'm not sure how you could show the tooltip at the cursor position. There probably is a way but it will be tricky. 

Maybe you could do something like that: https://jsfiddle.net/StephanWagner/apur420f/

**Comment by BoumBam** [comment]
to be more clear:
I'm using that <div  contenteditable="true"> </div>

I'm making facebook similar tag(mention).
If user tape a name, I get that name from database by ajax and show the ajax result in the popover.

The problem is if that div containt many text and user come at the top that div to tape a user name, the popover will be at the bottom of that div while the taped name and cursor are at the bottom. 

The popover does not follow cursor.
I want the popover to follow cursor.

**Comment by StephanWagner** [comment]
I don't think there is a proper solution to get the coordinates of the cursor in a contendeditable div or an textfield/textarea. I just tried google, but most results are to get the cursors position in terms of characters. And even that seems tricky.

If you do find a way to get the x/y coordinates of a cursor and still need help, feel free to reopen this issue.

**Comment by BoumBam** [comment]
But some tag mention plug-in show popover near the position of cursor:
Some plug-in like:
[https://github.com/luatnd/jquery-mentiony](url)
and:
[https://www.jqueryscript.net/demo/Twitter-Like-Mentions-Auto-Suggesting-Plugin-with-jQuery-Bootstrap-Suggest/](url)

I can't use them for many reasons.

They maybe can give you some ideas.

Thanks and i like you plug-in, It helps me too much.

**Comment by BoumBam** [comment]
> If you do find a way to get the x/y coordinates of a cursor and still need help, feel free to reopen this issue.

[https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_mouse_screenxy_clientxy](url)

**Comment by StephanWagner** [comment]
Ok, so thats what I came up with: https://jsfiddle.net/StephanWagner/apur420f/22/
