### ISSUE TITLE
Tooltip position near window boundaries

### ISSUE THREAD

**Issue by Tack0** [StephanWagner/jBox#135]
hello there,

i've developed since long time ago in vb6 an application for control of operations in real time (using a modified gantt) in a siderurgical company. i'm trying to migrate this app to web environment using c# and devxpress and  i'm using your jbox control to give tooltip functionality for the control, but when the pointer is near the boundaries of the screen limits the tooltip doesn't show as a normal but compressed windows or doesn't show inmediately below the pointer, i'll send you images and fragments of the code for you to see if there are any solution to this problem.

thanks in advance,

Tack0

pls send me an email for send you the image since this form doesn't allow to upload images (at least for me)

**Comment by StephanWagner** [comment]
You can send them to stephanwagner.me@gmail.com
