### ISSUE TITLE
Tooltip disappears when I move my mouse to it

### ISSUE THREAD

**Issue by DaWe35** [StephanWagner/jBox#139]
Tooltip disappears when I move my mouse to the actual tooltip (.jBox-wrapper).

**Comment by StephanWagner** [comment]
This is intended. Try the option closeOnMouseleave. When this option is set to true the tooltip should stay open when you move the move over it.

**Comment by DaWe35** [comment]
Wow, great job, thank you! I'm amazed, I spent some hours on finding the best tooltip js. And I think this is it :)
(why closeOnMouseleave = true isn't the default?)

**Comment by ibrahima** [comment]
Perhaps part of the confusion is regarding the naming. My interpretation of "close on mouse leave" is that if `false`, the jBox will **not** close when the mouse leaves, and when `true`, the jBox will in fact close when the mouse leaves. I would argue that the documentation also gives that impression:

> Close jBox when the mouse leaves the jBox area or the area of the attached element

Given that that is the description of the option, I would expect that true makes it do that, and false makes it not close when the mouse leaves the jBox area or the attached element.

Anyway, just wanted to share my thoughts. Thank you for jBox! It is a great library overall. This one option has actually tripped me up several times over the years though.
