### ISSUE TITLE
Remove footer after is set ? (overwrite options for a declared jbox)

### ISSUE THREAD

**Issue by quasiperfect** [StephanWagner/jBox#140]
hi i like jobx and tried to use it in a project where based on some ajax responses i need to overwrite the settings for a already opened jbox any idea on how i could achieve that ?

**Comment by StephanWagner** [comment]
Options can be overwritten with `jBoxReferenceVariable.option.optionName = 'newValue'`.

In your case it's a little bit more complicated though. Once jBox is created, you can only remove the footer with a jQuery selector. Remember that a jBox only gets created when it first opens though. You can change that with the option `createOnInit`.

Here is an example how you could da that: https://jsfiddle.net/StephanWagner/nz78bL6v/
