### ISSUE TITLE
JBox Tooltip can not caculate the position correctly when appended to an element which is not body

### ISSUE THREAD

**Issue by bayegy** [StephanWagner/jBox#141]
Dear developers,

There is a case when I need to append JBox Tooltip to an element (using appendTo option) but 
 not jQuery('body'), so when I scroll this element, the JBox Tooltip will move with.

But the problem is that JBox place the Tooltip in wrong position. Is there any way in which I can fix this?

Here is the code i used:

`var jbox=new jBox('Tooltip', {
        appendTo: jQuery('#cloud-app'),
        width: 310,
        theme: 'TooltipError',
        addClass: 'LoginTooltipError',
        target: jQuery('#input-name'),
        position: {
          x: 'left',
          y: 'top'
        },
        outside: 'y',
        offset: {
          y: 6,
          x: 8
        },
        pointer: 'left:17',
        animation: 'move'
      });
jbox.setContent("message").open();`

Thanks!

**Comment by StephanWagner** [comment]
Not sure how I can reproduce the issue. That's what I came up with: https://jsfiddle.net/StephanWagner/kqom3e62/

The `appendTo` option should be used carefully though as the position calculations are quite complicated then and some might not work at all.

It might work better without the `appendTo` option?! https://jsfiddle.net/StephanWagner/kqom3e62/2/

Or maybe you can explain in more detail what you are trying to achieve? Feel free to edit the fiddle with an example.
