### ISSUE TITLE
[suggestion] add option to hide title

### ISSUE THREAD

**Issue by despecial** [StephanWagner/jBox#143]
Currently I use the onOpen function to find the jBox title and hide it.
An option would be nice or if the title is empty, so none is shown in the modal.

**Comment by StephanWagner** [comment]
There shouldn't be a title when you don't set the `title` option.

If you want to hide the title at a later time, you could remove the `div` with `myModal.wrapper.find('.jBox-title').remove()`. See this fiddle https://jsfiddle.net/StephanWagner/mj5rkhs7/

You won't be able to use the method `setTitle()` afterward though, as jBox still has a reference to the title. If you want it more dynamic you could do it like that: 

```
myModal.titleContainer.remove();
delete myModal.titleContainer;
delete myModal.title;
```
See here: https://jsfiddle.net/StephanWagner/mj5rkhs7/7/

Also, notice that jBox does not reposition when you set the title. You will have to do that manually: https://jsfiddle.net/StephanWagner/mj5rkhs7/9/

**Comment by StephanWagner** [comment]
Oh, maybe I should also mention that an empty string `''` will create the title elements but leave them empty. If you do not want that jBox creates the title you should use `null`: https://jsfiddle.net/StephanWagner/0Lym4k5q/

**Comment by despecial** [comment]
Ah, I didn't think of trying NULL for the title. My bad.
Of course this works as mentioned. Thanks for the other ideas/suggestions!
