### ISSUE TITLE
target not working on modal

### ISSUE THREAD

**Issue by despecial** [StephanWagner/jBox#144]
Using the following code, I try to open the modal next to a div

```
	if( $('.callback_request').length) {
		new jBox('Modal', {
		  attach: '#openCallback',
		  title: '',
		  content: $('#callbackInfo'),
		  width: 320,
		  onOpen: function() {
			this.content.parent().find('.jBox-title').css({display: 'none'});
		  },
		  outside: 'x',
		  target: $('.callback_content'),
		  animation: 'flip'
		});
	}
```

The modal opens but the content is not in the viewport

**Comment by StephanWagner** [comment]
Not sure how to reproduce this issue. See this fiddle: https://jsfiddle.net/StephanWagner/9472nwub/
That's how I set it up and it seems to work fine. Feel free to edit the fiddle to reproduce the issue.

Also, see comment here: https://github.com/StephanWagner/jBox/issues/143#issuecomment-611154993
You need to use `null` to not set an title. An empty string `''` will set an empty title.

And I'm also not quite sure what you are trying to achieve with `outside: 'x'`. Modals are by default positioned in the center, horizontally and vertically.

**Comment by despecial** [comment]
Thx outside: 'x' was left from the experiment with position. But as soon as I use a target, the modal wont show up, only the overlay background.

This is the output:
`<div id="jBox1" class="jBox-wrapper jBox-Modal jBox-Default" style="position: fixed; display: block; opacity: 1; z-index: 10000; inset: 1608.35px auto auto 682px;"><div class="jBox-container"><div class="jBox-title" style="display: none;"><div></div></div><div class="jBox-content" style="width: 320px; height: auto;"><div style="display: block;" id="callbackInfo" data-jbox-content-appended="1"><p>Popup content</p></div></div></div></div>`

**Comment by StephanWagner** [comment]
The position values of a modal are by default `center`. When you want it outside of the target element along the x axis you need to set the position to:
```
position: {
  x: 'right',
  y: 'center'
},
outside: 'x'
```
See updated this fiddle: https://jsfiddle.net/StephanWagner/9472nwub/8/

**Comment by despecial** [comment]
Cool fiddle (also with the missing overlay). But it's not working on our live page.
This is the code. It loads, but the modal is not in the viewport/visible

```
		new jBox('Modal', {
		  attach: '#openCallback',
		  title: null,
		  content: $('#callbackInfo'),
		  width: 320,
		  animation: 'flip',
		  position: {
		  	x: 'right',
		    y: 'center'
		  },
		  outside: 'x',
		  target: $('.callback_content'),
		  overlay: false,
		  offset: {
			x: 15
		  }
		});
```

**Comment by StephanWagner** [comment]
Then the only explanation I have would be that the target div stretches over the whole page. Like that: https://jsfiddle.net/StephanWagner/9472nwub/9/

When there is not enough space available for the modal to show, jBox does some calculations to where position it best, but when the target element fills the whole page it won't work.

**Comment by despecial** [comment]
I wish it would be like that.

<img width="1608" alt="Screenshot" src="https://user-images.githubusercontent.com/4135109/78948067-806e1500-7ac7-11ea-8221-0082ba0abcde.png">

**Comment by StephanWagner** [comment]
Hmm, very strange. I'm also confused why it would set `inset: 94.5px auto auto 680px;`. I can't really help though without being able to reproduce the issue.

I'll close this one for now, but if you want, you can send me an email with the HTML and then I'll have a more detailed look: stephanwagner.me@gmail.com
