### ISSUE TITLE
Content with checkbox jumps in a draggable modal

### ISSUE THREAD

**Issue by IVoyt** [StephanWagner/jBox#146]
Hi! First of all thanks for this cool plugin!

Now the bug :) If content inside draggable modal has checkbox somewhere out of viewport (y-scroll) and if you mark that checkbox then content will immediately scroll up which is unexpected

**Comment by StephanWagner** [comment]
It seems to jump when draggable is `true`: https://jsfiddle.net/StephanWagner/qkbo6h05/2/

The content actually jumps when you click anywhere in the scrollable div, it doesn't have to be a click on a checkbox.

It does work when you set it to `title`: https://jsfiddle.net/StephanWagner/qkbo6h05/

**Comment by StephanWagner** [comment]
Closing and suggesting to use a draggable element or title when the jBox should be interactive and draggable at the same time.
