### ISSUE TITLE
onOpen: How to close all open modals?

### ISSUE THREAD

**Issue by despecial** [StephanWagner/jBox#147]
Modals are created without setting a variable for them, so I don't know which ones are already visible. Is there a function to close all other modals when opening one?

**Comment by StephanWagner** [comment]
I'm not sure how to do that with no saved variable. You could save a reference in an array and loop through that: https://jsfiddle.net/StephanWagner/10o2xun4/

**Comment by despecial** [comment]
That's the problem. The modals come from different scripts and templates, so that I cannot tell if they have a reference or just the instance itself. I assumed there was a possibility to catch all instances and modify them.

**Comment by StephanWagner** [comment]
Unfortunately, there is no global collection. I'll keep this issue in mind and might add this functionality in the future.
