### ISSUE TITLE
Dynamiv tooltip content not loading

### ISSUE THREAD

**Issue by despecial** [StephanWagner/jBox#148]
I updated to the latest version of jBox (1.2.0) and jQuery. Previously all worked fine with this code

js:
```
    alltooltips = new jBox('Tooltip', {
        attach: '.tooltip, .infotip',
        getTitle: 'data-tooltip-title',
        content: $('.tooltip-content'),
        pointer: 'center:-50',
        maxWidth: 320,
        minWidth: 200,
        adjustPosition: true,
        adjustTracker: true,
        delayOpen: 300,
        trigger: ("ontouchend" in document.documentElement) ? 'touchend' : 'mouseenter',
        closeOnEsc: true,
        closeOnClick: true,
        closeOnMouseleave: true,
        onOpen: function () {
            var id = this.source.attr('data-tooltip-content');
            this.content.find('.tooltip-content').addClass("hide");
            this.content.find('.tooltip-content-' + id).removeClass("hide");
        }
    });
```

In the html:
```
<div class="tooltip-content tooltip-content-ttip1 hide">
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet</p>
</div>
<div class="tooltip-content tooltip-content-ttip2 hide">
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet</p>
</div>
<div class="tooltip-content tooltip-content-ttip3 hide">
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet </p>
</div>
```

The tooltip shows up, also the title but content stays empty.
The "hide" class gets removed but the containing html is not loaded into the div.
If I debug this.content I get the class jBox-content instead of the one using in the script.

**Comment by StephanWagner** [comment]
I had to change a couple of things in your example:
- The class-name when adding the hide class should be `.find('.tooltip-content-ttip' + id)`
- When jBox grabs content, it adds the style `display: block`, that's why I used CSS `.hide { display: none !important; }` so that the hide class will overwrite the style.

Then it does work: https://jsfiddle.net/StephanWagner/b207fx4u/

**Comment by despecial** [comment]
Unfortunately it is still not working. content doesnt find "tooltip-content".
When I put it to console log, the `id` is correct but `this.content.find('.tooltip-content-' + id)` shows this:
```
{…}
length: 0
prevObject: Object { 0: div.jBox-content, length: 1, prevObject: {…} }
<prototype>: Object { jquery: "3.5.1", constructor: S(e, t), length: 0, … }
app.js:184:21
```

**Comment by StephanWagner** [comment]
Strange. Do these elements exist when jBox opens the first time? Also, are you initializing jBox in Domready?

$(document).ready(function() {
  new jBox('Tooltip', {
    // ...
  });
});

jBox will grab those elements the first time it opens. If you want jBox to grab them when it initializes, you have to use the option `createOnInit`.

**Comment by despecial** [comment]
Weird. It was the same code as before. The tooltips are present (in the footer) and I was calling the jbox script in `!function ($) { }(jQuery);` Not sure if the new jQuery version is the problem. Those calls worked before. Now I moved the call to $(document).ready... and there we are. All fine.

Any idea why this happens? Thanks for the help!

**Comment by StephanWagner** [comment]
Na, I'm not sure, I always used `$(document).ready(`. Glad it worked out!
