### ISSUE TITLE
Modal bewegt sich bei Ajax-Inhalten

### ISSUE THREAD

**Issue by ponchotobi** [StephanWagner/jBox#149]
Hallo,
vielen Dank für jBox! 

Wenn ich ein einfaches Modal öffne und mittels Ajax Inhalt lade, dann öffnet sich das Modal zwar, aber nicht in seiner Endposition in der Mitte der Seite. Es öffnet sich immer ein wenig weiter unten rechts und springt dann in die Mitte der Endposition. 

Folgender Code: 
$('.testmodal').on('click', function () {
	new jBox('Modal', {		
	    title: 'bla',
	    ajax: {
	        url: 'bla.php'
	    }
	}).open();
});

**Comment by StephanWagner** [comment]
Das passiert, weil jBox nicht wissen kann wie groß der Inhalt ist der mit ajax geladen wird. Wenn der Inhalt geladen ist, schreibt jBox das geladene HTML in den content bereich und positioniert sich dann neu.

Es gibt zwei Möglichkeiten das zu verhindern: 

1.) Du kannst die Option `setContent` auf `false` setzen und dann in der `success` Methode vom Ajax call den content manuell selber setzen (ohne `setContent` zu verwenden). Dann ist das Modal allerdings nicht genau zentriert positioniert.

2.) Setze eine Weite und Höhe des Modals. Somit ist das Modal bereits richtig positioniert wenn der AJAX call gemacht wird.

Closing as this is not an issue that needs fixing, it's intended so.
