### ISSUE TITLE
Click on tooltip, affect the element under the tooltip

### ISSUE THREAD

**Issue by wobility** [StephanWagner/jBox#152]
Hello,

I don't understand why but all my click on the tooltip go through the popup and click on the element under the tooltip !? Also the closeButton appear on my tooltip but not working, and no cursor pointer. Do you know if it's possible when I click on the tooltip open has no effect on  the element under the tooltip.

**MY CONFIGURATION**

> i class="sl sl-icon-question toolTipBox icone_blue_txt_white" title="text content in my tooltip with Jbox" /i

>         var myjBox = new jBox('Tooltip', {
>             attach: '.toolTipBox',
>             theme: 'TooltipSmallGray',
>             adjustPosition: true,
>             adjustTracker: true,
>             maxWidth : 400,
>             fade : 400,
>             animation: {open: 'pulse', close: 'zoomIn'},
>             closeButton : true,
>             closeOnEsc : true,
>             closeOnClick : true,
>             trigger : 'click',
>         });

**Comment by wobility** [comment]
With the param closeOnClick : true The tooltip closed when I click all over the document but if I don't add this parameter the close button doesn't work

**Comment by wobility** [comment]
Ok I don't know why and if it's normal but I do change like this to fix this behavior  : 

FROM

> .jBox-TooltipSmallGray{pointer-events:none}

TO

> .jBox-TooltipSmallGray{pointer-events:visible}

**Comment by StephanWagner** [comment]
Closing as this behaviour is intended with that theme.
