### ISSUE TITLE
Modal resize on open ajax

### ISSUE THREAD

**Issue by OswaldoMM** [StephanWagner/jBox#157]
Hi, Stephan!
I have an issue with a modal jBox... I'm calling a php page with ajax and the result is setted inside the jBox modal... But inside there is a datatable result; so, the table is filled and the jBox modal gets the 100% height of the table, but the table is resized and not the modal...  (Sorry for my bad English). See:

![Sin título](https://user-images.githubusercontent.com/21183018/99184353-31005f00-2710-11eb-9077-f88f934c736b.png)

So, I have to click on the modal title to get it resized:

![Sin título2](https://user-images.githubusercontent.com/21183018/99184381-5e4d0d00-2710-11eb-9916-efdf67fa2c05.png)

Can you help me? Is there any programatically "code-thing" I can use to avoid this behavior?
Thanks in advance!!!

My code is:
```
$(document).ready(function() {
    var pop = new jBox('Modal', {
        width: '600',
        height: 'auto',
        closeButton: "title",
        draggable: true,
        repositionOnOpen: true,
        repositionOnContent: true,
        onOpen: function(){
            this.position({
                position: {x: 'center', y: 'center'},
                adjustPosition: true, 
                adjustTracker: true, 
                reposition: true
            })
        }
    });
        
    $("#btn-cii").click(function(e){
        e.preventDefault();
        pop
        .setTitle("Códigos CIIU")
        .ajax({
            url: '/web/lis/Lista_Codigos_CIIU.php',
            reload: 'strict',
            setContent: true,
            success: function () {
                this.open();
            }
        });
    });
});
```

**Comment by StephanWagner** [comment]
You can manually resize and position jBox width `pop.position();`. jBox will do this automatically when the ajax call is finished, but when the size changes afterwards, you'd have to do it manually.

**Comment by OswaldoMM** [comment]
Hmmm, ok.
I'll try that... Thank you!
