### ISSUE TITLE
Confirm onClick on Mobile mode

### ISSUE THREAD

**Issue by OswaldoMM** [StephanWagner/jBox#159]
Hi Stephan!
I was testing Confirm modals (Chrome -> Developer Tools) and I found that when it's on mobile mode, confirmButton and cancelButton aren't responding (they do not 'click')... So I modify Jbox.all.min.js file...

`html(this.options.cancelButton).click(function()......`
with
`html(this.options.cancelButton).on("click tap touchstart",function()......`

and

`this.submitButton.off("click.jBox-Confirm"+this.id).on("click.jBox-Confirm"+this.id......`
with
`this.submitButton.off("click tap touchstart.jBox-Confirm"+this.id).on("click tap touchstart.jBox-Confirm"+this.id`

Hope it helps...

**Comment by StephanWagner** [comment]
Hmm, seems chrome changed the click event, previously I believe a click event was automatically converted to tab.

Thanks for the info... Will fix!

**Comment by StephanWagner** [comment]
Should be fixed with Version v1.2.1
