### ISSUE TITLE
bug: closeOnClick work only after second open method

### ISSUE THREAD

**Issue by 6elkir** [StephanWagner/jBox#163]
Close option "closeOnClick" not work after $(...).open({closeOnClick: 'body'}), but start working after second call open.

**Comment by 6elkir** [comment]
Check all releases after 0.6.4 - bug submit, in version 0.6.4 work without bug. Omg!

**Comment by 6elkir** [comment]
Bug example:

`var tooltip = new jBox
            (
                'Tooltip',
                {
                    'responsiveHeight' : false,
                }
            );

        tooltip  . setContent ( 'abc' );
        tooltip  . open ( {'closeOnClick':'body', 'target': $('.class')} );
`

**Comment by StephanWagner** [comment]
You have to set the option `closeOnClick` initially when creating the jBox. There are only a few options you can pass to the `open` method. See here: https://stephanwagner.me/jBox/methods#open-and-close

```
var tooltip = new jBox('Tooltip', {
  'responsiveHeight' : false,
  'closeOnClick': 'body'
});

tooltip.setContent ( 'abc' );

tooltip.open({
  'target': $('.class')
});
```
