### ISSUE TITLE
Disable buttons after confim

### ISSUE THREAD

**Issue by BytesAhead** [StephanWagner/jBox#168]
Hi,

Amazing library, thank you for keeping it up to date!

The library doesn't seem to expose any methods to disable/enable the buttons.  I've tried all methods I can think of and I can't disable the confirm button after it's been pressed, either by means of finding the button or via the dialog.  I'd like to disable it until an operation has been completed, then either re-enable the button of close the dialog.

var updateCustomerModal = new jBox('Confirm', {
    content: "Update Customer?",
    cancelButton: 'No',
    confirmButton: 'Yes',
    closeOnConfirm: false,
    closeOnEsc: true,
    onOpen: function () {
    },
    confirm: function () {
//Disable buttons here
        updateCustomerModal.setContent("Updating customer..");
       // Operation
//Enable buttons here
    }
}).open();

Thanks,
Brent.

**Comment by StephanWagner** [comment]
Bit tricky, but doable:

See here: https://jsfiddle.net/StephanWagner/g3qtms7n/

When the jBox is created you'll have to update the default events on the cancel button:

```javascript
onCreated: function() {
  this.wrapper.find('.jBox-Confirm-button-cancel')
    .off('click tap')
    .on('click tap', function() {
      // Here we abort if the buttons are disabled
      if (updateCustomerModal.disableButtons) {
        return false;
      }
      updateCustomerModal.close();
    });
},
```

Then in the confirm function you'll have to check too if they are disabled:

```javascript
// Abort if buttons are disabled
if (updateCustomerModal.disableButtons) {
  return false;
}

// Disable buttons here
updateCustomerModal.disableButtons = true;
```

I also added a little CSS and following JS so that the user sees that a request is in process. That's how I handle my requests anyways:

```
// Set loading status
updateCustomerModal.wrapper.find('.jBox-Confirm-button').addClass('button-disabled');
updateCustomerModal.wrapper.find('.jBox-Confirm-button-submit').addClass('loading-bar');
```

**Comment by BytesAhead** [comment]
Perfect! Great solution, works well, many thanks for your time! I've seen others ask the same question, do you have a FAQ of these solutions you do? - it would be really useful! Thanks again Stephan.

**Comment by StephanWagner** [comment]
I do have a couple of demos here: https://stephanwagner.me/jBox/demos
I always wanted to add more there but didn't really have the time to do so.
