### ISSUE TITLE
How i register scroll event on main block with jbox options ? 

### ISSUE THREAD

**Issue by andrew781026** [StephanWagner/jBox#181]
did there any options in jbox , I can setting for the scrolling event ( other then windows ) to reposition tooltip ? 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10812707/131306879-7c6b6874-d139-4105-94d8-1f2b3cfb8692.gif)

Currently , I use onCreated to listen the scrolling event 

But , I called `new jBox` many times , so I want setting the scrolling event  globally , How can I do that ? 

```javascript

  /*!
   * Determine if an element is in the viewport
   * (c) 2017 Chris Ferdinandi, MIT License, https://gomakethings.com
   * @param  {Node}    elem The element
   * @return {Boolean}      Returns true if element is in the viewport
   */
  var isInViewport = function (elem) {
    var distance = elem.getBoundingClientRect();
    return (
      distance.top >= 0 &&
      distance.left >= 0 &&
      distance.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
      distance.right <= (window.innerWidth || document.documentElement.clientWidth)
    );
  };


  const registerScrollPosition = ($contents, myTooltip) => {

    if ($contents && $contents.length > 0) {

      $contents.on('scroll', () => {

        $selector = myTooltip.target

        if (isInViewport($selector.get(0))) myTooltip.position()
        else myTooltip.close()
      })
    }
  }


  const myTooltip = new jBox('Tooltip', {
    attach: '.filter-select',
    content: $('.fri-dropdown'),
    trigger: 'click',
    adjustPosition: true,
    outside: 'y',
    position: {
      y: 'bottom',
    },
    addClass: 'select-dropdown',
    onCreated: function() {

      registerScrollPosition($('main.content'), this)
    },
  })
```

**Comment by StephanWagner** [comment]
Can you try `adjustTracker: true`. See here: https://stephanwagner.me/jBox/options#position

**Comment by andrew781026** [comment]
I forgot to mention , the scroll bar is not on body it's on $('main.content') object 

![2021-08-30_13h57_03](https://user-images.githubusercontent.com/10812707/131426791-15718718-4f79-4fb2-b784-f815972f4cd3.png)

P.S.   I tried  `adjustTracker: true`  below `adjustPosition: true`  but It didn't work  (ノへ￣、)

**Comment by StephanWagner** [comment]
Then you have to manually trigger the `position()` method when the are is being scrolled:

```javascript
$('.right').on('scroll', function () {
  myTooltip.position();
});
```

See an example here: https://jsfiddle.net/StephanWagner/1s8hcwtz/1/

**Comment by andrew781026** [comment]
@StephanWagner thanks your answering 😊

I solved the problem 😎
