### ISSUE TITLE
Tooltip - best way to grab element to use as content

### ISSUE THREAD

**Issue by redtopia** [StephanWagner/jBox#184]
What's the best way to specify an element in the DOM that I want to use as tooltip content? The way I'm currently doing it, I add it to the jBox window via the onOpen() event callback and then calling the setContent() method. Doing it this way, I have to clone my DOM element otherwise it doesn't exist the next time the tooltip is rendered.

I'm wondering if there's a better way to do it.

Here's my code... this renders a tooltip to the right of a feature description link.

```
<table id="feature-matrix">
<tr>
    <td><a href="#" data-feature="feature1">feature 1</a></td>
</tr>
</table>
<div id="feature-descriptions" class="hidden">
    <div  data-feature="feature1">
        <p>This is the best feature ever! <a href="#">Click here for more info</a></p>
    </div>
</div>

<script>
$(document).ready(function () {
    var matrix= $('#feature-matrix'),
        descriptions = $('#feature-descriptions');
    new jBox('Tooltip', {
        attach: $('a[data-feature]', tbl),
        position: {x: 'right', y: 'center'},
        outside: 'x',
        offset: {x: 15, y: 0},
        maxWidth: 400,
        trigger: 'click',
        closeOnClick: 'body',
        onOpen: function () {
            // get the feature description to display in the tooltip
            var feature = this.source.attr('data-feature'),
                featureDesc = $('[data-feature="' + feature + '"]', descriptions),
                content;
            if (featureDesc.length) {
                content = $(featureDesc).clone();
                this.setContent(content);
            }
        }
    });
});
</script>
```

**Comment by StephanWagner** [comment]
Thats how I usually do it too.

Depending on the use case, I sometimes append the element to the jBox content area rather than cloning and then I hide all elements exept the current one in the onOpen method.

**Comment by redtopia** [comment]
Interesting... I can see how that would work. By the wayt, where is the best place to ask questions?
