### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by lippylion** [StephanWagner/jBox#195]
Hi]

Using your jBox for the first time and not that experienced.

How can I, if possible link an html pages content into a modal. e.g take the whole page using an Ajax link on a page to open the modal, that then loads the content of the html file as a whole. Or have you another way to do this within JBox. Currently use magnific, that will alow me to do this and the html contents appear in the popup window.

Another question, sorry, but can you load a notice or modal on page load or is that not yet possible.

Examples please if its possible.

thanks, like the plugin wanted something for tooltip, which is great..

thanks

**Comment by StephanWagner** [comment]
You could load html by ajax and then use the `.setContent()` method to set it as the modals content. If you want to load a conplete HTML file, the only way I see would be an iFrame: https://jsfiddle.net/StephanWagner/39jwncu2/

You can load jBoxes whenever DOM is ready, thats what i did in the example with the iFrame: https://jsfiddle.net/StephanWagner/39jwncu2/

On page load: https://jsfiddle.net/StephanWagner/ohaxqsft/

**Comment by lippylion** [comment]
Hi thanks for the examples, much appreciated.

Regards the iframe content, is there  a way of being able to set the html page outside the jquery.

I have a scoreboard html file for 4 quizzes. Each quiz has a separate name. Quiz one, quiz two etc..

If someone clicks the link show scoreboard for quiz one, then it should load quiz one scoreboard. 

1. do i have to create several jquery calls for each quiz.
2. or can i set the content via php so that the jquery call via the variable ill now which quiz.xx to load.

Finally got the tooltip working and managed to style it , great by the wway. Notices are really  handy, especially when I can now load on page load.

thanks again.
