### ISSUE TITLE
Closing jBox from Content

### ISSUE THREAD

**Issue by teamayu** [StephanWagner/jBox#197]
Hi Stephan,

Fantastic little plugin, thank you.

Can I close the jBox from content I create after I have triggered another function? Example:

```
function custom() { 
 // do something
}
var myModal = new jBox('Modal', {
   title       : 'title here',
   content     : '<button class="btn" onclick="custom();myModal.close()">Process & Close</button>',
   footer      : 'footer here'
 });
 myModal.open();
```

Many thanks.

**Comment by StephanWagner** [comment]
Sure,

One way would be to store jBox in a global variable and use the `.close()` method:

```javascript
var myModal;

$(document).ready(function() {

  function custom() {
    // do something
  }

  myModal = new jBox('Modal', {
    title: 'title here',
    content: '<button onclick="myModal.close()">Process & Close</button>',
    footer: 'footer here'
  });
  myModal.open();

});
```

See here: https://jsfiddle.net/StephanWagner/7cLzuxf2/1/

-- 
Stephan Wagner
Philipp-Häring-Str. 8
86157 Augsburg

+49 176 45783473
https://stephanwagner.me

**Comment by teamayu** [comment]
Yep, that works like a charm, thanks Stephan, appreciate it,
