### ISSUE TITLE
IE8 Modal windows createElementNS

### ISSUE THREAD

**Issue by lbineau** [StephanWagner/jBox#20]
Hi,

I've just discovered your plugin, it's really usefull thank you !
However I got a problem with IE8 when you launch a modal, it throws an error about createElementNS.
The problem is just when you call a modal, tooltips and notices are working well.

![image](https://cloud.githubusercontent.com/assets/1534688/4589519/cef0aeac-5054-11e4-8f2b-4ed5e3d104d0.png)
![image](https://cloud.githubusercontent.com/assets/1534688/4589515/b99822f6-5054-11e4-8280-f7001354b074.png)

Any idea ?

**Comment by StephanWagner** [comment]
0.4.0 is out, IE8 is not supported anymore
