### ISSUE TITLE
jbox tooltip stay on screen after element destroyed

### ISSUE THREAD

**Issue by hmzlam** [StephanWagner/jBox#210]
i have a div with a tooltip
after the user click on it all the table is refreshed with new data, which means original div is destroyed, the jbox tooltip  stays open and no way to close it

**Comment by StephanWagner** [comment]
You can always close your jBox manually with `myjBox.close()` when you save it as a variable:

```
var myjBox = new jBox('Tooltip');

myjBox.open();

myjBox.close();
```
