### ISSUE TITLE
Close all tooltips when opening new

### ISSUE THREAD

**Issue by JayH77** [StephanWagner/jBox#213]
Hi,

Really like this plugin, but I'm having a few issues.

I have a table and in each row, there's an info icon with a jbox tooltip that contains a few links and I'm using the delayClose option.

Is there a way to close all open tooltips when a new tooltip is opened?

Thank you

**Comment by StephanWagner** [comment]
Actually, my approach would be to use one jBox and update the content once it opens. Something like that: https://jsfiddle.net/StephanWagner/f0q8ax1u/

Another way would be to close them manually (notice the `ignoreDelay` flag) when saving them in a variable: 
https://jsfiddle.net/StephanWagner/wagnoc3t/

The first approch is defenitely cleaner and more performant.
