### ISSUE TITLE
Confirm type: option target doesn't work

### ISSUE THREAD

**Issue by zWeRz** [StephanWagner/jBox#33]
I expected confirm modal dialog to be near the 'target', but it is actually in the center of the screen.
Here some code:

$(this).jBox('Confirm', {
            confirmButton: 'Remove',
            cancelButton: 'Cancel',
            target: $('#chart1'),
            confirm: function() {
                chart.remove();
            }
});

**Comment by StephanWagner** [comment]
Hmm, true, definitely worth looking into.

If you want to move the jBox near an element, try playing around with the position, outside and pointer options. Check out this fiddle, there I moved the jBox to the left of the target element and added a pointer:
http://jsfiddle.net/StephanWagner/pL2ncyr0/
