### ISSUE TITLE
Open modal after ajax-request complite.

### ISSUE THREAD

**Issue by Rad1calDreamer** [StephanWagner/jBox#36]
How i can show my modal only after i get content from ajax&? it's need to correct work open's animation effect

**Comment by StephanWagner** [comment]
You would have to create an ajax wrapper as jBoxes ajax function is triggered when jBox opens. Try something like that:
```
var myJBox = new jBox('...');

$.ajax({
  //...
  success: function () {
    myJBox.open();
  }
});
```
