### ISSUE TITLE
can i don't close the window when click overlay on `Confirm` model?

### ISSUE THREAD

**Issue by huguangju** [StephanWagner/jBox#39]
> demo: [http://jsfiddle.net/hacrmgef/2/](http://jsfiddle.net/hacrmgef/2/)

``` javascript
new jBox('Confirm', {
    attach: $('.delFs'),
    width: 300,
    title: 'remove bound',
    overlay: true,
    content: $('#delConnContainer')
});
```

use `Confirm` ask sb. whether to do sth., i am don't expect close the window when sb. click the overlay,here provide a  option cancel the behaviour?

**Comment by StephanWagner** [comment]
That'll be option closeOnClick: false
See https://stephanwagner.me/jBox/options#closing-jbox
