### ISSUE TITLE
adaptive size on mobile device

### ISSUE THREAD

**Issue by Rad1calDreamer** [StephanWagner/jBox#40]
Hi.
Help me please.
I have normal modal window on pc
![capture image](https://cloud.githubusercontent.com/assets/7055577/7061615/17551314-de9d-11e4-84f7-5a9ce9782f15.png)

but it's not resize on mobile 
![screenshot_2015-04-09-09-43-43](https://cloud.githubusercontent.com/assets/7055577/7061623/2760d662-de9d-11e4-913a-2c6fc08ca9d5.png)

how i can fix it?
Thx

**Comment by StephanWagner** [comment]
Sorry for late reply, have been neglecting jBox for a while... You can try the responsive Version now: v0.4.0
