### ISSUE TITLE
can not scroll the multiple choice select element through mouse wheel on popup window

### ISSUE THREAD

**Issue by huguangju** [StephanWagner/jBox#42]
can not scroll the multiple choice select element through mouse wheel and touch pad on popup window.

> only can use the left mouse button
> mac 10.10.2 chrome 42.0.2311.90 (64-bit)

see [http://jsfiddle.net/mbzg79ke/1/](http://jsfiddle.net/mbzg79ke/1/)

**Comment by StephanWagner** [comment]
Sorry for late reply... I have been neglecting jBox for a while.
In case you're still interested: Use option {isolateScroll: false} to fix this: http://jsfiddle.net/StephanWagner/mbzg79ke/2/
