### ISSUE TITLE
recalculate coordinates after changing target position

### ISSUE THREAD

**Issue by milaza** [StephanWagner/jBox#47]
How I can to force modal window to recalculate coordinates after changing target position (for example after scrolling). As I see "repositionOnOpen" option make this, but I can't get it to work.

**Comment by StephanWagner** [comment]
If this is still an issue, try using the option `{adjustTracker: true}`
Also, you can always build your own trackers, e.g. 

```
new jBox('Modal', {
  // ...
  onOpen: function () {
    $(window).on('scroll.jBox', function () { this.position(); }.bind(this));
  },
  onCloseComplete: function () {
    $(window).off('scroll.jBox', function () { this.position(); }.bind(this));
  } 
});
```
