### ISSUE TITLE
Stop closing on mouseleave when it's hovered again

### ISSUE THREAD

**Issue by chang-zhao** [StephanWagner/jBox#50]
It would be very useful as a popover with some UI elements,
if an accidental short mouseleave, as well as having an offset,
would not close the popover (which makes it useless).

**Comment by StephanWagner** [comment]
Sorry for late reply, I have been neglecting jBox for a while.

If this is still an issue, check out this fiddle: http://jsfiddle.net/StephanWagner/6mbL3exd/

You can just add a closeDelay and open up the jBox again when the mouse moves into the jBox within that time.

```
new jBox('Tooltip', {
    attach: $('[data-JBOX]'),
    offset: {y: -10},
    delayClose: 200,
    onCreated: function () {
      this.wrapper.on('mouseenter.jBoxCreatedEvent', function () {
        this.open();
      }.bind(this)).on('mouseleave.jBoxCreatedEvent', function () {
        this.close();
      }.bind(this));
    }
  });
```
