### ISSUE TITLE
Allow adjustPosition "move" without having a pointer

### ISSUE THREAD

**Issue by chang-zhao** [StephanWagner/jBox#51]
I don't understand, why that "pointer" is needed for the reposition,
it's just a picture!
How can having the picture of an arrow relate to a capability of a program?

**Comment by StephanWagner** [comment]
Hey chang-zhan, actually the adjustPosition: 'move' option is intended to move the content of the jBox when there is not enough space to show the full tooltip. For example when the pointer points to a target and the tooltips content area reaches out of the viewport. Then the jBox will be moved so it is within the viewport and the pointer still points towards the target area.

Now with responsive support as of v0.4.0 all jBoxes will be adjusted to be within the viewport. But the adjustPosition: 'move' option still behaves as before.
