### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by mwaschkowski** [StephanWagner/jBox#52]
Hi,

I'm working in a Knack environment (knackhq.com) and if I load jbox as shown here, it works fine:

![image](https://cloud.githubusercontent.com/assets/1027250/8412012/05f5e52e-1e55-11e5-950f-53c119722fba.png)

However, I would like to simply copy and past jBox into the Javascript window, but it then silently fails - as soon as it reaches 

```
var modal = new jBox('Confirm', {...
```

later in the code it says that jBox is not loaded. Is there something preventing jBox from loading?

I tried to use your cdn (even though you suggested not to), but I can't do that either as the CDN is http, and I'm coming from https.

The reason its an issue is because the clients I'm creating this for don't have their own server, its all hosted on Knack.

Not sure why it silently fails, is there anything I can do to try and figure out better what is going on?

Thank you,

Mark

**Comment by StephanWagner** [comment]
Sorry, I've been neglecting jBox for a while, I'm just going through the issues now.

Im closing this one as it is old and this is probably resolved. If not, feel free to open it up again or create a new one.
