### ISSUE TITLE
Feature detection instead of browser sniffing ? 

### ISSUE THREAD

**Issue by gautamz07** [StephanWagner/jBox#54]
Hello Stephan,

This is a very impressive plugin, i just had some time today, this is not really an issue , but you have the following lines in your code : 

// I know browser detection is bad practice, but for now it seems the only option to get jBox working in IE8
        var userAgent = navigator.userAgent.toLowerCase();
        this.IE8 = userAgent.indexOf('msie') != -1 && parseInt(userAgent.split('msie')[1]) == 8;

why don't you replace this with feature detection I.E. to check if a browser supports a certain property or not ? This is just a suggestion.  Although your approach is much more straightforward, its know to be not so full proof . Feature detection on the other hand is much more accurate.  What do you think ? 

The line of code i am talking about can be found here https://github.com/StephanWagner/jBox/blob/master/Source/jBox.js#L445

**Comment by StephanWagner** [comment]
Yeah, feature detection have been much better, guess I didn't care enough about IE8.
Anyways, closing this issue as version 0.4.0 just came out and this one dropped IE8 support
