### ISSUE TITLE
Ajax is firing two times..

### ISSUE THREAD

**Issue by johnarc5** [StephanWagner/jBox#60]
Hey i am using latesh jbox plugin and i am having an issue with that like ajax is firing incrementally every  time..and how can i set style with content returned via ajax.

 <button type="button" class="am-btn am-btn-default" id="listmodel_{{$page->id}}" onclick="list('{{$page->id}}')" ><span class="am-icon-pencil-square-o"></span> Shared User List</button>

<script type="text/javascript">
    function list(id){
        alert()
        $('#listmodel_'+id).jBox('Modal', {
            ajax: {
                url: 'userlist',
                data: 'id='+id,
                title:'User List',
                animation: 'zoomIn',
                width:300,
                height:250,
                setContent: true,
                spinner: true,
                reload: true
            }
        });
    }
</script>

**Comment by StephanWagner** [comment]
Sorry, I have been neglecting jBox for a while. If this is still an issue, check out this fiddle: http://jsfiddle.net/StephanWagner/f09g1L7b/3/
Always remember to only create one instance of jBox for a specific purpose.
