### ISSUE TITLE
Positioning problem

### ISSUE THREAD

**Issue by raducretu** [StephanWagner/jBox#61]
Hi there,

I have the following issue:
The modal jBox is not positioning correct. There is no negative margin cu center it. The code I use:

```
    $(function() {
        $('.dct-class').each(function(){
            var $modal = new jBox('Modal', {
                attach: $(this),
                content: $(this).data('dct-content')
            });
        });
    });
```

Thanks,
Radu

**Comment by StephanWagner** [comment]
Works fine in this fiddle: http://jsfiddle.net/StephanWagner/3f2wmwkt/
Also, always remember to only create one jBox instance for a specific purpose. Feel free to open this issue up again if you still have trouble.
