### ISSUE TITLE
Nothing happens on option relative or fixed

### ISSUE THREAD

**Issue by rochapablo** [StephanWagner/jBox#64]
After open the tooltip and scrolling the page, the element always get fixed on my screen.

I had tried the attributes **positions** that the jBox allow me use, but nothing seems change.

![to1](https://cloud.githubusercontent.com/assets/5365304/15195605/ea969758-179e-11e6-9f16-951c884d498e.PNG)

![to2](https://cloud.githubusercontent.com/assets/5365304/15195618/f15cafc8-179e-11e6-9a9b-aac05ac3bac4.PNG)

```
id: `tt-${$scope.playlist}`,
attach: $(`#tt-${$scope.playlist}`),
content: $(`#ttc-${$scope.playlist}`),
width: 262,
height: 319,
trigger: 'click',
closeOnClick: 'body',
closeOnEsc: true,
```

**Comment by StephanWagner** [comment]
Is your Tooltip attached to a fixed element?

If so, try the following options:

http://stephanwagner.me/jBox/options <http://stephanwagner.me/jBox/options>
fixed	boolean	Sets a fixed position rather than an absolute
reposition	boolean	Recalculates the position when the browser size changes


Cheers,
Stephan

**Comment by rochapablo** [comment]
I've just did

```
fixed: true/false,
reposition: true/false,
```

... but it seems that nothing changes.

**Comment by StephanWagner** [comment]
Could you make a fiddle which reproduces this behavior? https://jsfiddle.net/9nheaa8z/
Then I'll figure out a way to make it work.

**Comment by rochapablo** [comment]
I'm working on it, just give some time and I'll share the link.

**Comment by rochapablo** [comment]
Unfortunately I tried to reproduce the behavior, but [it worked](http://codepen.io/rochapablo/pen/PzoYxm).

Well I guess that I will have to check piece by piece until fix that.

Anyway, thank you for your time.

**Comment by rochapablo** [comment]
Sorry, but know I was able to reproduce [the problem](http://codepen.io/rochapablo/pen/PzoYxm).

Well I guess that because my content contains the scroll (not the body) that's why the jBox is fixed.

**Comment by StephanWagner** [comment]
I see. Actually, I think I came across this problem before. I noted it on my TODO list. For now, what you can try is to manually trigger jBoxes .position() method in the scroll event. Check out this fiddle which might help you out how to manually position a jBox: http://jsfiddle.net/StephanWagner/ftofeo4e/3/

**Comment by rochapablo** [comment]
Thank you man!

I'm living here what I did. Just in case.

```
onOpen: function() {
	$('#md-scroll').scroll(function() {
		jjbox.position();
	});
	$scope.items = [
		{ name: 'One' },
		{ name: 'Four' }
	];
}
```

Where ``` $('#md-scroll') ``` is the div that has the tscroll-bar.

Thank you again.
