### ISSUE TITLE
Jbox responsiveness

### ISSUE THREAD

**Issue by robertpmansion** [StephanWagner/jBox#65]
Any update on updating the js code to become responsive?

**Comment by StephanWagner** [comment]
Yes, I finally started working on it. But I'm travelling right now, so I have limited access to Internet. I try to do as much as I can on localhost when I have time. I'm not sure yet when the first 0.4 Version will be released.

**Comment by StephanWagner** [comment]
Just released 0.4.0 with responsive support: https://github.com/StephanWagner/jBox/releases/tag/v0.4.0
