### ISSUE TITLE
Jbox not positioning in the center in some mobile devices

### ISSUE THREAD

**Issue by robertpmansion** [StephanWagner/jBox#67]
Hi Stephan,

I'm trying out your latest release of jBox, great work on releasing the responsive fix. However when I tried this on some mobile device like Samsung Galaxy S5, jBox does not re-position to center. Please see the image below. 

![image](https://cloud.githubusercontent.com/assets/18090549/20250113/345af7ca-aa44-11e6-8135-5e11c43d5015.png)

**Comment by StephanWagner** [comment]
Hmm, strange works fine on my iphone 6. But thats the only device I tested it with yet... I'll look into it!

**Comment by StephanWagner** [comment]
Yeah, there is definitely a bug somewhere... I just reproduced the issue with google chromes device toolbar. It seems to work fine when I open it in vertical view. But when I rotate view, open jBox Modal, then rotate back, it calculates the position wrongly.

**Comment by StephanWagner** [comment]
I just committed some changes to master... can you check if this bug is fixed?
https://github.com/StephanWagner/jBox/archive/master.zip

**Comment by robertpmansion** [comment]
Fixed.
