### ISSUE TITLE
using <a> href for ajax

### ISSUE THREAD

**Issue by robertpmansion** [StephanWagner/jBox#68]
Hi Stephan,

It would be good to have something that would indicate <a> href as ajax request and will get the content of that request and place to jBox content. What do you think? :)

**Comment by StephanWagner** [comment]
You should be able to do this by setting the getURL option:

```
ajax: {
   // ...
   getURL: 'href'
}
```
Haven't tested this yet, but it should work. If not feel free to reopen this issue and I'll have a more detailed look at this
