### ISSUE TITLE
Confirm jBox is crashed

### ISSUE THREAD

**Issue by OswaldoMM** [StephanWagner/jBox#71]
Hi!
I just don't know what I'm doing wrong...
But Confirm Modal is not working...
This is my code:
```
var conf = new jBox('Confirm', {
                title: 'Confirmar',
                theme: 'TooltipBorder',
                overlay: 'own',
                content: 'Al hacer esto, eliminará el archivo actual. ¿Deseas continuar?',
                confirmButton: 'Sí',
                cancelButton: 'No',
                confirm: function(){
                	cnf.close();
                }
            });
conf.open();
```
When I open it, this looks like this:
![sin titulo](https://cloud.githubusercontent.com/assets/21183018/20629424/7ee1f448-b2f9-11e6-97a5-513bff14a60d.png)
I'm using the last version of jBox that you have posted.

Thanks in advance!

**Comment by StephanWagner** [comment]
Looks like the plugin is not loaded, 

make sure to include the files

Sourece/plugins/Confirm/jBox.Confirm.js   and
Source/plugins/Confirm/jBox.Confirm.css

Let me know if that solved it!

Cheers,
Stephan

**Comment by OswaldoMM** [comment]
Holy God!
Man, Thank you...
Sorry, I used jBox several years ago... But it's been a long time without upgrade it...
Today, I downloaded last version. And all just crashed out: notices, modals and confirms.

I had combined all js files and all css files.
I have a lot of pages, I can't modify them all.

It seems to work perfectly now...
