### ISSUE TITLE
Notice position

### ISSUE THREAD

**Issue by OswaldoMM** [StephanWagner/jBox#72]
Hi!
It's me again...
Now, I have an issue with the positions of the Notices...
All them appears at the bottom-left of the window...
But my code tells another thing:
```
new jBox('Notice', {
	autoClose: 2000,
	color: 'blue',
	position: { x: 'center', y: 'center' },
	content: "Registro actualizado"
});
```
![image](https://cloud.githubusercontent.com/assets/21183018/20632699/7dd7fd36-b30d-11e6-8900-9c23dbe355b4.png)
It worked fine with an older version... I have downloaded 0.4.2 version, today.

Thanks in advance!

**Comment by StephanWagner** [comment]
Hmm, yeah, so actually I don't think that should have worked before either then... I'll look into it, the whole positioning was rewritten.

You could use following code to imitate a notice, see this fiddle: https://jsfiddle.net/StephanWagner/xsrjcjqk/2/

```
new jBox('Modal', {
  addClass: 'jBox-Notice jBox-Notice-blue',
  autoClose: 2000,
  position: { x: 'center', y: 'center' },
  content: "Registro actualizado",
  overlay: false,
  closeOnClick: 'box',
  onCloseComplete: function () {
    this.destroy();
  }
}).open();

```

**Comment by OswaldoMM** [comment]
Oh, man!
You are a monster!
Hell yes! That code works fine!!!
Nice!!!!

The only issue is that... I have hundreds of Notices around the application...
:(

I'll have to do something for this kind of changes...

Thanks a lot!

**Comment by StephanWagner** [comment]
You could make use of the new plugin option and create your own Notice plugin.
See here: https://jsfiddle.net/StephanWagner/x2du4Ldy/1/

Remove the file Source/plugins/Notice/jBox.Notice.js

Then create your own Notice plugin:

```
new jBoxPlugin('Notice', {
  color: null,
  stack: true,
  stackSpacing: 10,
  autoClose: 2000,
  position: {
    x: 'center',
    y: 'center'
  },
  target: jQuery(window),
  fixed: true,
  animation: 'zoomIn',
  closeOnClick: 'box',
  zIndex: 12000,

  _onInit: function ()
  {
    // If jBox grabs an element as content, crab a clone instead
    this.options.content instanceof jQuery && (this.options.content = this.options.content.clone().attr('id', ''));

    this.open();
  },

  _onCreated: function ()
  {
    // Add color class
    this.wrapper.addClass('jBox-Notice-color jBox-Notice-' + (this.options.color || 'gray'));

    // Store position in jBox wrapper
    this.wrapper.data('jBox-Notice-position', this.options.attributes.x + '-' + this.options.attributes.y);
  },

  _onOpen: function ()
  {
    // Loop through notices at same window corner and either move or destroy them
    jQuery.each(jQuery('.jBox-Notice'), function (index, el)
    {
      el = jQuery(el);

      // Abort if the element is this notice or when it's not at the same position
      if (el.attr('id') == this.id || el.data('jBox-Notice-position') != this.options.attributes.x + '-' + this.options.attributes.y) return;

      // Remove notice when we don't wont to stack them
      if (!this.options.stack) {
        el.data('jBox').close({ignoreDelay: true});
        return;
      }

      // Get the new margin and add to notices
      var margin = (el.data('jBoxNoticeMargin') ? parseInt(el.data('jBoxNoticeMargin')) : parseInt(el.css('margin-' + this.options.attributes.y))) + this.wrapper.outerHeight() + this.options.stackSpacing;
      el.data('jBoxNoticeMargin', margin);
      el.css('margin-' + this.options.attributes.y, margin);

    }.bind(this));
  },

  _onCloseComplete: function ()
  {
    this.destroy();
  }

});
```

**Comment by OswaldoMM** [comment]
Hi, Stephen. 
Years ago, I sent you some issues about Notices position...
Now, I have a question about the position of all JBoxes (notices, confirms, modals).

Look at this example:
![image](https://user-images.githubusercontent.com/21183018/47184701-fa697780-d2f0-11e8-81e1-c4d4dade0b2e.png)
This link opens a window inside an iFrame... This iFrame has 1600px height.

Now, when I use a JBox, no matter it was, it is trying to center at the 1600px height:
![image](https://user-images.githubusercontent.com/21183018/47184813-4caa9880-d2f1-11e8-9ee8-9dfe38cdd865.png)
Then, I have to scroll down to find the centered JBox:
![image](https://user-images.githubusercontent.com/21183018/47184832-59c78780-d2f1-11e8-9ade-d854fb491d42.png)

My question is:
Is there a way to center the JBox at the center of the screen and NOT at the center of its container?

**Comment by OswaldoMM** [comment]
Oh! I forgot to tell you... JBox version is the latest... 0.4.9

Thanks in advance!
