### ISSUE TITLE
Multiple Open Boxes

### ISSUE THREAD

**Issue by johnrickman** [StephanWagner/jBox#74]
I need to have multiple boxes open at the same time. Easy!

However, closing the active box also closes all inactive boxes. I noticed that closing a box removes all jbox related classes on <body>. Is this the cause for this behavior?

Is there any work around for this?

**Comment by StephanWagner** [comment]
Shouldn't actually. Which version are you using? What kind of jBoxes? And through what action are they closed? like a click on the overlay?

**Comment by johnrickman** [comment]
Each box is created
```
var org_window = new jBox('Modal', {
					width: 880,
					height: 600,
					content: $('#orgwindow'),
					closeOnClick:false,
					onOpen:function() {
						
					},
					onClose:function() {

					}
				});
```

opened
`org_window.open()`

and closed by the top right x button.

**Comment by johnrickman** [comment]
Im assuming that the top right close button is a global close as well as pressing the escape key. Guess I need to close it via org_window.close();

**Comment by StephanWagner** [comment]
So if each jBox instance refers to the same variable `org_window` then you can really only use one jBox with it, the last one in this case. Also when you use an element as content, in this case `$('#orgwindow')` then the content will be moved from one jBox to the other.

I made a fiddle where you can use multiple jBoxes with the same content element: https://jsfiddle.net/StephanWagner/vzh25zph/1/

You can update this fiddle to show me what you'd like to do and I'll have another look.

**Comment by johnrickman** [comment]
Oops, each box has its own variable, but defined in the same manner.

**Comment by StephanWagner** [comment]
Ah I see, check put this fiddle: https://jsfiddle.net/StephanWagner/vzh25zph/2/

Is that kinda what you'd like to do?

**Comment by johnrickman** [comment]
Exactly

**Comment by johnrickman** [comment]
Im not getting the close button in the top right of the box however.

**Comment by johnrickman** [comment]
However, the close button in the top right of the box isn't appearing.

**Comment by StephanWagner** [comment]
Sorry, fiddle was wrong, its not `closeOnClick`, is option `closeButton`: https://jsfiddle.net/StephanWagner/vzh25zph/6/

See also: https://stephanwagner.me/jBox/options#closing-jbox

**Comment by johnrickman** [comment]
Perfect, thanks!
