### ISSUE TITLE
Jbox Modal window disappears if browser window is resized vertically too small

### ISSUE THREAD

**Issue by Movax12** [StephanWagner/jBox#75]
When I resize the browser horizontally, all is good.
If I resize it vertically I see this element changes until top reaches 'auto':
```
<div id="jBox2" class="jBox-wrapper jBox-Modal jBox-Default jBox-hasTitle jBox-closeButton-title" style="position: fixed; display: block; opacity: 1; z-index: 10000; top: auto; left: auto; right: auto; bottom: auto;">
```

If top reaches auto, the window disappears. Chrome console says:
Uncaught TypeError: Cannot read property 'outerHeight' of undefined

**Comment by StephanWagner** [comment]
Are you using the newest version? Sounds like a bug I fixed in 0.4.7
If it's the newest Version, at what browser size does the error occur? When the jBox wrapper reaches the viewport edges or before that?

**Comment by Movax12** [comment]
Hi,
Thanks for replying quickly. 
I upgraded to the newest version, and it is the same. It happens when the modal window touches the top of the browser. I see in your demo page the behavior is okay. ( https://stephanwagner.me/jBox/ )
In that case, the element top changes to a negative value. For me, it changes to top:auto and I get the console error on every resize until I make the vertical large enough again.

Try here: http://www.tier2computing.com and click on request service and resize the window.

**Comment by StephanWagner** [comment]
Ok, I'll close it...
If the error comes up again and you have an example page or fiddle where I can reproduce the error, open it up again and I'll have a look.
