### ISSUE TITLE
I have close button in overlay

### ISSUE THREAD

**Issue by gitdust** [StephanWagner/jBox#76]
hi,when I open a jbox and at the top right position in overlay element,I got a close button,I do not know how to cancel it.

**Comment by StephanWagner** [comment]
You can set the option closeButton to false. See more about closing a jBox here: https://stephanwagner.me/jBox/options#closing-jbox

**Comment by gitdust** [comment]
that button is on the overlay element,not the button on the title.
it's a SVG element.
I do not know how to disable it.
-_-!!!

**Comment by StephanWagner** [comment]
Should work just fine: https://jsfiddle.net/StephanWagner/0rsLh7cb/

**Comment by gitdust** [comment]
Thank you for your patience！！！
In the '#jBox-overlay' element , I got these elements : 
```
<div class="jBox-closeButton jBox-noDrag">
    <svg viewBox="0 0 24 24">
        <path d="M22.2,4c0,0,0.5,0.6,0,1.1l-6.8,6.8l6.9,6.9c0.5,0.5,0,1.1,0,1.1L20,22.3c0,0-0.6,0.5-1.1,0L12,15.4l-6.9,6.9c-0.5,0.5-1.1,0-1.1,0L1.7,20c0,0-0.5-0.6,0-1.1L8.6,12L1.7,5.1C1.2,4.6,1.7,4,1.7,4L4,1.7c0,0,0.6-0.5,1.1,0L12,8.5l6.8-6.8c0.5-0.5,1.1,0,1.1,0L22.2,4z"></path>
    </svg>
</div>
```

**Comment by StephanWagner** [comment]
Yes, thats the close button. Just check out the fiddle I posted, you can use the option `closeButton: false` to remove it: 

Without close button: https://jsfiddle.net/StephanWagner/0rsLh7cb/
With close button: https://jsfiddle.net/StephanWagner/0rsLh7cb/3/

Feel free to update the fiddle to reproduce the issue you are having.

**Comment by gitdust** [comment]
Yes, but what really puzzles me is  if  I set the option like this : 
`
closeButton: 'title'
`
I got two close button , one is on the title and the other one is on the overlay !

**Comment by gitdust** [comment]
and also if I set the option:
`closeButton: false`
I still got a close button on the overlay!

**Comment by StephanWagner** [comment]
Can you show me an example, seems to work fine here:
https://jsfiddle.net/StephanWagner/0rsLh7cb/4/

Also, which version are you using, the newest one?

**Comment by gitdust** [comment]
no ,not the newest one, it's 0.3.2.

**Comment by gitdust** [comment]
I have updated it to the newest version and it work fine.
I have downloaded it for a long time and did not realize the updating.
Thanks for your patience,again!!!

**Comment by StephanWagner** [comment]
Ok, I think I know what's happening, in version 0.3.2 jBox still shares the overlay, which I changed in a sub-version of 0.4. 

You can try the following: In the onOpen method of the jBox which only should have the closeButton in the title, hide the button with CSS, and when jBox is closed, show it again.

add following to the options:

```
onOpen: function () {
  $('body').addClass('jBoxHideCloseButton');
},
onCloseComplete: function () {
  $('body').removeClass('jBoxHideCloseButton');
}
```

And add following CSS to your CSS file:

```
.jBoxHideCloseButton .jBox-closeButton {
  display: none;
}
```

See this fiddle:
https://jsfiddle.net/StephanWagner/c729na2s/1/

**Comment by StephanWagner** [comment]
Oh OK, just seen you updated... Glad its works now.
If you have more questions, feel free to open another issue!
