### ISSUE TITLE
Notice problem

### ISSUE THREAD

**Issue by gitdust** [StephanWagner/jBox#77]
Hi, it's me again.
When I updated to the newest version. I had some Notice using problems.
`
function FailNotice(msg){
    new jBox('Notice', { content: msg, color: 'red' });
}
`
when I call this function ,it does not show a notice box.I need to modify it to this:
`
function FailNotice(msg){
    new jBox('Notice', { content: msg, color: 'red'}).open();
}
`
and it shows a notice box, but it's on the middle of page and it has no style which it should have a red background.
I have seen the example[https://jsfiddle.net/StephanWagner/hpa1qpz9/], but it can not work in my project.

**Comment by StephanWagner** [comment]
Don't use `.open()`, notices open automatically, your code should work just fine.

With jBox 0.4.0 the types Notice, Image and Confirm are now plugins.

You need to include the css and js files for the plugin, located at `/Source/plugin/Notice/jBox.Notice.js` and `/Source/plugins/Notice/jBox.Notice.css`

**Comment by gitdust** [comment]
Done.
Much thanks.
I really should read the documentation again.It has changed a lot.

**Comment by StephanWagner** [comment]
No worries! Let me know when you run into trouble again.
