### ISSUE TITLE
closeButton option doesn't work on open() method

### ISSUE THREAD

**Issue by pudd** [StephanWagner/jBox#78]
I use the closeButton: true as an option but there is not close button on the modal

**Comment by StephanWagner** [comment]
There should be: https://jsfiddle.net/StephanWagner/tzuhzozf/
Feel free to update the fiddle to reproduce the issue you are having.

**Comment by mhulse** [comment]
Looks like it happens when I have `getTitle: 'ds-modal-title',` specified.

**Comment by Mikk3lRo** [comment]
The problem actually exists even with a "normal" `title: 'whatever'` option too:
https://jsfiddle.net/Mikk3lRo/tzuhzozf/6/

The [PR](https://github.com/StephanWagner/jBox/pull/95) I just sent should fix it, can you confirm @mhulse ?

**Comment by StephanWagner** [comment]
I merged the request to master. I will also add some other stuff from my todo list over the weekend and should be releasing a new version then.

**Comment by mhulse** [comment]
Looks like that fixed it for my use case! Thanks @Mikk3lRo and @StephanWagner! Much appreciated.

Also, nbd, but I noticed the min version needs an update. I figure you'll update over the weekend. Let me know if you want a PR for that.

**Comment by Mikk3lRo** [comment]
That is probably more or less my fault - I haven't made any changes to that in my PR's... I assumed that @StephanWagner handled that as part of some sort of release procedure, so I didn't want to include "unrelated" changes (and maybe use a different minifier from what Stephan prefers)...

For future reference: Should I / contributors update the minified version too when sending PR's?

**Comment by mhulse** [comment]
> I assumed that @StephanWagner handled that as part of some sort of release procedure, so I didn't want to include "unrelated" changes (and maybe use a different minifier from what Stephan prefers)...

Totally. I usually think the same thing about stuff like that. Some folks like specific options set when uglifying JS. In the case of something like normalize.css, the author there doesn't even include a min version as he assumes most people will be including that code as a part of their own minification/build process (personally, I like it when repos offer both a min and un-min/uglified versions).
