### ISSUE TITLE
No color on jBox Notices

### ISSUE THREAD

**Issue by OswaldoMM** [StephanWagner/jBox#80]
Hi!
Long time I don't write to you!

I have updated jBox to 0.4.7 version.
But since then, all notices seem had lost the background color, as you can see it here:

![image](https://cloud.githubusercontent.com/assets/21183018/22386026/36280180-e4a3-11e6-9aa4-d6b4522b1b14.png)

The code I'm using to create Notices is this, you wrote it!:
`function jsNotices(atCl, clr, message, url){
	new jBox('Modal', {
		addClass: 'jBox-Notice jBox-Notice-'+clr,
		autoClose: atCl,
		position: { x: 'center', y: 'center' },
		content: message,
		overlay: false,
		closeOnClick: 'box',
		onCloseComplete: function () {
			if(url.trim() !== ""){
				window.location.href = url;
			}
			this.destroy();
		}
	}).open();
}`

Where: 
* atCl is the time of autoClose (i.e. 2000)
* clr is the color (i.e. blue)
* message is the message (doh!) (i.e. 'Registro actualizado')
* url is an URL if I  wanna changed location (i.e. '/Basicas/tiposUnidades.html')

The resources are located like this:

/resources/
  + /css/
    jBox.css
    + /plugins/
      + /Confirm/css and js
      + /Image/css and js
      + /Notice/css and js
  + /js/
    jBox.min.js
    jquery.min.js
    ... all others js's

I just don't know what I'm doing wrong... I have just updated version.

Thanks in advance!!!!

**Comment by StephanWagner** [comment]
Hi,
Strange, your code works in this fiddle: https://jsfiddle.net/StephanWagner/x7qg54kk/ <https://jsfiddle.net/StephanWagner/x7qg54kk/>
make sure to use lowercase color names…

Thats the external resources in this fiddle:


did that help?
Stephan

**Comment by OswaldoMM** [comment]
Hi, Stephen!
Thanks for your support...

After reading your message, I "magically" decided to include these lines in jBox.css:

`@import url("../css/plugins/Confirm/jBox.Confirm.css");
@import url("../css/plugins/Image/jBox.Image.css");
@import url("../css/plugins/Notice/jBox.Notice.css");`

And now it is working fine...

Just a question: Is it necesary to do this thing everytime I update jBox?

Thanks a lot!

**Comment by StephanWagner** [comment]
No you shouldn't have to. As of version 0.4.0 the types Notice/Image/Confirm are not included by default, that's why you need to include them manually as they are plugins now.

**Comment by OswaldoMM** [comment]
You are right!
Thank you very much!
