### ISSUE TITLE
Ajax tooltips are not being positioned correctly

### ISSUE THREAD

**Issue by ericbae** [StephanWagner/jBox#81]
This worked quite well in the older version. But the latest version doesn't seem to position the tooltips correctly after the AJAX content is loaded.

I know there is an option "repositionOnContent" and I tried that and it still doesn't seem to work.

Any ideas?

<img width="461" alt="screen shot 2017-01-30 at 9 18 22 pm" src="https://cloud.githubusercontent.com/assets/614459/22419450/aad503ee-e731-11e6-9be5-1d0dcc499a04.png">

**Comment by StephanWagner** [comment]
Yeah, this seems to be an issue... I added the option spinnerReposition, but it doesn't seem to work properly. Can you try to add following code to your ajax object in the options: 

```
complete: function () {
  this.position();
}
```

See this fiddle: https://jsfiddle.net/StephanWagner/bs7e57uk/

I'll try to fix this issue soon.

**Comment by ericbae** [comment]
Hi @StephanWagner 

Apologies for the late response to this, I did try your suggestion and it works fine. 👍
