### ISSUE TITLE
.attach not working

### ISSUE THREAD

**Issue by Movax12** [StephanWagner/jBox#82]
Hi,

I might be doing something wrong, but shouldn't this work? It looks like jbox is attaching, but it never loads:

https://jsfiddle.net/w7n6ysgb/

**Comment by StephanWagner** [comment]
jBox needs to be initialised when DOM is ready... this one works: https://jsfiddle.net/StephanWagner/w7n6ysgb/1/

**Comment by Movax12** [comment]
Hi,

I can get it to work as in the jsfiddle, but the real issue is this: I am loading part of a page via ajax in another $(document).ready(function() { }) which then needs to re-attach the jbox to the new content. Chrome console says: 
```
(index):379 Uncaught ReferenceError: stickymod is not defined
```
(stickymod being the name of my jbox)

If I define the object globally first, I get: 
```
Uncaught TypeError: Cannot read property 'attach' of undefined
```
Is there a way to get that working?

**Comment by Movax12** [comment]
Hi. I got this working. I was declaring the jBox object in the $(document).ready(function() { }) with `var` making it inaccessible globally. Working now, thanks for your help.
