### ISSUE TITLE
Multiple Events Possible

### ISSUE THREAD

**Issue by cycomachead** [StephanWagner/jBox#83]
Is it possible to have an item triggered by multiple events, like `mouseenter, touchclick`?

It doesn't seem like the current version supports this in a basic test I tried but I might have set something up wrong...

**Comment by StephanWagner** [comment]
You would have to do it manually. I haven't gotten around to include proper eventhandling for mobile devices. I'll mark this issue as enhancement.

To set the events manually, check out this fiddle: https://jsfiddle.net/StephanWagner/gnmaydos/1/
I didn't test it yet on a mobile device though.

**Comment by cycomachead** [comment]
Thanks, that's a really helpful example and makes sense!
