### ISSUE TITLE
Issue importing with NPM

### ISSUE THREAD

**Issue by MartinDM** [StephanWagner/jBox#84]
I have a build script which states:
`var jBox = require('jBox');`
Which my build script (using Browserify) reports `Cannot find module 'jBox'...  `

The docs on using this with npm seem to skim over the steps in doing so. Can you say if jBox needs to be imported in some specific way with a specific name?

I can confirm the module is downloaded into node_modules, but still the import fails. Any ideas?

Thanks.

**Comment by jgoldhammer** [comment]
I have the same issue. It is a blocker for me at the moment...
I think jbox is missing the typical exports statements

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.jBox = factory());
}(this, (function () { 'use strict';
...

@StephanWagner, do you have time to do that?

**Comment by jgoldhammer** [comment]
Some reference how to do that:
http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/

**Comment by askoutaris** [comment]
That's an important issue for us too! It's a wonderful plugin which makes our life really better, but now we switched to angular and we'd like to use jBox in conuction with angular and typescript...

Please let us know if you are planning to makes it work with these technologies. Thank you not only for this but also for the excellent plugin you have created!!

**Comment by jgoldhammer** [comment]
I have to switch to tooltipster which also works very great... And works with npm and webpack...

**Comment by StephanWagner** [comment]
Hi, I just got back from my travels and I'm gonna improve jBox the coming weeks. I'll look into it!

**Comment by JoepRoebroek** [comment]
Hey guys, this is due to the fact that the main key is missing from the package.json. I created a PR to fix this:  #85

**Comment by StephanWagner** [comment]
I just updated jBox to master with the AMD and CommonJS support with the guide from this page: http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/
Added the main key to the package.json as well
Can you guys have a look before I publish a new version?

**Comment by JoepRoebroek** [comment]
@StephanWagner Yeah that's better than my PR. Thanks :+1: i'll check if it works in our project tomorrow.

**Comment by jgoldhammer** [comment]
@StephanWagner For me it works fine.

**Comment by smarterdigitalltd** [comment]
@StephanWagner confirmed - npm import works for me too using files from the master branch of this repo

**Comment by StephanWagner** [comment]
Just published v0.4.8 with AMD and CommonJS support. I'm not too familiar with AMD and CommonJS, so I'm not sure if the support needs to be included into the plugin files as well (e.g. /plugins/Image/jBox.Image.js). If so, open up this issue again and I'll add it.
