### ISSUE TITLE
Modal positioning not quite right until window resize

### ISSUE THREAD

**Issue by smarterdigitalltd** [StephanWagner/jBox#86]
Hello!

I'm really impressed with this plugin - it's very nice.

I am noticing a strange behaviour with modal positioning.

I have tried multiple configurations with the attributes and position attributes, but with no luck. It happens if I set 

position: { y: 'center', x: 'center' } 

or if I set 

position: { y: 'center', x: 'center' }, // or bottom/right or '0'/'0'
attributes: { y: 'top', 'x': 'left' } // or bottom/right

Modals that should be center/center are appearing lower than center. 

Some modals that should be bottom/right are appearing lower, whereas others have a gap at the bottom.

For example, I have a window height of 1103, the height of the modal is 402 (which leaves 701), but the top position of the modal is 466

If I change the size of the browser by dragging the edge, the positioning of all modals is recalculated and looks perfectly centered. Here's a quick screencast: https://goo.gl/De9wkG

I am using the master branch as of 06 May 2017.

If you can shed any light, I would really appreciate it, as it's otherwise the best modal/lightbox plugin I've ever seen :-)

**Comment by StephanWagner** [comment]
Hmm, this is strange behaviour. Is there any change for me to get a look at some code?
Or, could you reproduce the issue in jsfiddle. You can fork this one which has all the files included already https://jsfiddle.net/StephanWagner/ov6d6960/

**Comment by smarterdigitalltd** [comment]
Hey Stephan - thanks for the reply.

I was playing with this further and I'm pretty sure it's because of a sticky header on my site. The modal position was too low by 50% of the height of my sticky header + 10px (I'm not sure what the 10px is yet). That, and it positions perfectly on tablet view, when the sticky header is disabled.

The point is - I don't think I can successfully reproduce inside JS Fiddle.

With regards to code

```
    /**
     * Set popup params
     *
     * @since 1.0.0
     * @access private
     * @method _getPopupParameters
     * @param popup Object
     */
    _getPopupParameters (popup)
    {
        return {

            /**
             * Set the content element
             */
            content:            $(`#${WPDPopupConfig.wpdPopupCpt}-${popup.id}__content`),

            /**
             * Set the ID
             */
            id:                 `${WPDPopupConfig.wpdPopupCpt}-${popup.id}`,

            /**
             * Add a class to the wrapper
             */
            addClass:           `${WPDPopupConfig.wpdPopupCpt}-${popup.id}__container`,

            /**
             * Set popup dimensions
             */
            width:              popup.settings.width,
            height:             'auto',

            /**
             * Set the position & attributes
             */
            position: {
                x:              popup.settings.popup_type === 'fly_out' ? popup.settings.fly_out_x_position : 'center',
                y:              popup.settings.popup_type === 'fly_out' ? popup.settings.fly_out_y_position : 'center'
            },

            /**
             * Configure the design
             */
            overlay:            popup.settings.popup_type === 'modal',
            zIndex:             popup.settings.popup_type === 'modal' ? 9000 : 8900,

            /**
             * Configure animations
             */
            animation:          WPDBBPopupsFrontEnd._getAnimationParameters(popup),

            /**
             * Configure scroll attributes
             */
            blockScroll:        popup.settings.popup_type !== 'fly_out',
        }
    },
```

I instantiate jBox with the above params and then invoke .open() manually.

I think it's OK, and as per the docs, but it is just the sticky header which is causing a bit of an offset.

Thanks @StephanWagner

**Comment by smarterdigitalltd** [comment]
@StephanWagner - Perhaps I'm going slightly mad but I just rechecked, and contrary to my last message, the positioning is the same with NO sticky header... (ie it's bad until I manually adjust the screen size).

I can setup a private demo/example, if you'd like. Just let me know what you need.

**Comment by StephanWagner** [comment]
If I have access to an url where I can have a look at the source code, that should be enough for me to start debugging.

**Comment by StephanWagner** [comment]
Definitely strange behaviour! I'm having trouble debugging though as the frontend.js is minified. Could you send me the file unminified or the part which initialises the jBoxes? stephanwagner.me@gmail.com
