### ISSUE TITLE
IE8 not able to continue past jBox lib

### ISSUE THREAD

**Issue by MartinDM** [StephanWagner/jBox#87]
Hi

I'm finding that when the newest version of Jbox is `require`d into a script file, because it depends on the latest jQuery, IE8< logs an `unexpected identifier` error. 

I have handled the content without jBox for IE8, but how can the loading into `bundle.js` of the library itself be bypassed in the case of an older browser which doesn't support the jQuery dependency? Is this something I would need to add to the plugin itself? Can you advise on the lowest version of jquery jBox would work with?

Thanks in advance,

Martin

**Comment by StephanWagner** [comment]
Hi Martin,

IE8 support was dropped with version 0.4.0, see release notes here: https://github.com/StephanWagner/jBox/releases/tag/v0.4.0

So the latest for IE8 would be 0.3.2 but that's a really old version without responsiveness and probably quite a few bugs.

You could also consider just dropping IE8 support for your projects. Market share of IE8 dropped to nearly zero the last years, right now it's a mere 0.76% for desktop browsers and statistics for all platforms (including mobile, etc.) don't even show Internet Explorer anymore up to version 10:
http://gs.statcounter.com/browser-version-partially-combined-market-share#monthly-201611-201704
