### ISSUE TITLE
The overlay cannot cover outside of iframe.

### ISSUE THREAD

**Issue by yiddou** [StephanWagner/jBox#88]
The overlay cannot cover outside of iframe. I use the jbox in iframe, but I'd like the overlay can mask whole window not inside the iframe.

**Comment by StephanWagner** [comment]
It is actually quite complicate for the iframe content to communicate with the parent page. You can read more here: https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site
There are some solutions out there, but I wouldn't rely on any of them too much as this is highly browser dependent. It's just a huge safety issue when an iframe can control javascript from the parent page. I had this issue myself before and I just had to find a solution without an iframe.
It might be a bit easier if the iframe content is from the same domain as the parent page, but even then you should research if it'll work on all browsers and devices. 

If you do find a solution to reliably communicate between iframe and parent, the only way I can think of how to add an overlay is something like that:

onOpen: function () {
  yourReferenceToParentWindow.openOverlay();
},
onClose: function () {
  yourReferenceToParentWindow.closeOverlay();
}
the functions openOverlay and closeOverlay should then open and close the overlay at the parent page with same CSS and animation speed as the one from the iframe. And you'd also have to add close-buttons and events manually. Won't be easy, unfortunately.

If you do find a way and get stuck, send me a fiddle and I see if I can help out: https://jsfiddle.net/L35fLcLw/
