### ISSUE TITLE
content jumping on modal window show/hide

### ISSUE THREAD

**Issue by alarstyle** [StephanWagner/jBox#9]
When showing modal window scrolling should be disabled, but scroll bar still should be visible. 
It will prevent content jumping.

**Comment by SergiiShcherbak** [comment]
I used <a href="#">...</a> to display a modal, and had the same problem.

Here is a simple solution that worked: "**I think this is because your href is set to "#". Changing this fixed it for me**." (by [cpuguy83](https://github.com/jschr/bootstrap-modal/issues/131)).
