### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by cmann1** [StephanWagner/jBox#92]
After some use I have two suggestions:

1. An overlayClass option to  individually style overlays.
I've added this to the `_showOverlay` function:
`this.options.overlayClass && this.overlay.addClass(this.options.overlayClass);`

2. Also close on contextmenu when using `closeOnClick` and call `event.preventDefault();`

**Comment by StephanWagner** [comment]
Hi @cmann1

1. You can individually style overlays by referring to its id. Overlays get an id the format `JBOXID-overlay`.

2. We purposely don't call preventDefault when closing jBox. You can use the option `preventDefault`, this will prevent default click events on the attached element. Other than that you'd have to add preventDefault manually.

Cheers,
Stephan
