### ISSUE TITLE
closeOnMouseleave works when leaving tooltip but not attached element

### ISSUE THREAD

**Issue by taalas** [StephanWagner/jBox#93]
Hi,

i am using a jBox tooltip attached to an element with "closeOnMouseleave: true"

The tooltip closes when the mouse leaves the tooltip itself, but doesn't close if the mouse leaves the element it is attached to (a button in this case) and will stay open until the mouse entered and left the tooltip once.

Is this intended behaviour? Anything I can do to debug my case?

**Comment by Mikk3lRo** [comment]
Can you reproduce in a jsfiddle, post a link or supply some code that shows the behaviour?

You can modify this fiddle (which does currently close when leaving the button) if you want:
https://jsfiddle.net/omkdpdu3/1/

**Comment by taalas** [comment]
@Mikk3lRo Thanks for your reply.

I played with the fiddle you provided and it shows the same behaviour when adding

`trigger: 'click touchclick',`

to the jBox options. I forgot to mention that I was opening the tooltips with a click, but that should not change the close behaviour, should it? If you add the option to the fiddle the tooltip opens when the button is clicked, but only closes when the mouse enters and leaves the tooltip area, not the button area. So part of the onLeave is still working it seems...

**Comment by taalas** [comment]
Looking at the code it seems that the close event is only attached to the element itself if a mouseenter event was used to open it?

**Comment by StephanWagner** [comment]
The option adds a mouseleave event to the wrapper which checks if the mouse is not over the source event, if not it will close the jBox. It also overrides the default closing of the jBox. When the mouse leaves the source element it checks if the mouse now is over the jBox wrapper, if so, it won't close it.

The option trigger currently only supports 'mouseenter' or 'click', which I meant to improve ages ago but never got the time for it.

As @Mikk3lRo said, if you can provide a fiddle or some code we could have a detailed look at whats happening.

**Comment by taalas** [comment]
@StephanWagner Thanks for taking the time to look into this.

The following fiddle illustrates my point:
https://jsfiddle.net/omkdpdu3/3/

I removed the "touchlick" option (since it isn't supported if I understand you correctly). The tooltip opens upon clicking the button, it closes when entering and leaving the tooltip, but not when leaving the button.

**Comment by StephanWagner** [comment]
OK, now I understand what you are trying to do. You could add the mouseleave event mannually, check out the updated fiddle: https://jsfiddle.net/omkdpdu3/4/
Not sure how it behaves with touchclick though.

**Comment by taalas** [comment]
That works perfectly, thanks.

For touch devices I would need to add close on click I guess (since leave is not possible). The only problem with that is that I need the user to be able to click something inside the tooltip without it closing. I tried the 'body' option, but since I fetch the content from outside the tooltip, it closes as soon as the user clicks inside the tooltip (it contains a calender in this case) which is not intended...

**Comment by StephanWagner** [comment]
There are a few things you can do.
Add the option closeOnClick, this will close the jBox on mobile devices when you click anywhere but the jBox. Also you can add your own close buttons. Check out the updated fiddle: https://jsfiddle.net/omkdpdu3/6/
