### ISSUE TITLE
Scroll moves when open Modal

### ISSUE THREAD

**Issue by OswaldoMM** [StephanWagner/jBox#94]
Hi! It's me again...
There is an issue that I can't resolve, maybe you can help me... :)

I have this page with scroll, I'm moving it down for select a row:
![image](https://user-images.githubusercontent.com/21183018/31320328-5c762a62-ac38-11e7-8d8d-b8fc156c20b4.png)

These icons open a modal popup with the selected row data:
![image](https://user-images.githubusercontent.com/21183018/31320339-98f01cfa-ac38-11e7-9cb2-3b65e7984009.png)

When the jBox is opened, the scroll of the main window moves up, at the very top; I'm missing the row I had selected (I mean, I don't know what was the row I opened):
![image](https://user-images.githubusercontent.com/21183018/31320369-295d956a-ac39-11e7-8cbf-546cf4b54ce9.png)

Can you help me? 
Thanks in advance

**Comment by StephanWagner** [comment]
It seems to have something to do with the option blockscroll. See here: https://stephanwagner.me/jBox/options#other-options

Try to set this option to false and see if that fixes the issue.

If not, let me know and I'll have a more detailed look at it.

**Comment by OswaldoMM** [comment]
Hi, Stephan. Thanks for the answer.
This is the code I use to open the modal:

```
new jBox('Modal',{
    title: "..:: Detalles de la Unidad ::..",
    content: $('#popEditUnidad'),
    blockScroll: false
}).open();
```

I tried by setting it to true (blockScroll), and it did not work either...
Even I delete all others options, like repositionOnOpen or overlay...
It keeps moving the scroll automatically to the top.

Thanks in advance.
:) 👍

**Comment by StephanWagner** [comment]
Hmm,
I just created a fiddle with your code and I can't reproduce the issue: https://jsfiddle.net/StephanWagner/gd4rhz1h/

In this fiddle it doesn't scroll to top no matter if `blockscroll` is `false` or `true`.

Just for understanding, do you open the modal with `.open()` or do you attach it to the edit elements?

**Comment by OswaldoMM** [comment]
Mmm...
Let me see...
1. I'm here, and click that button:
![image](https://user-images.githubusercontent.com/21183018/31321017-21dc1d88-ac44-11e7-989c-f8feddb76937.png)

2. That button scrolls down with this code:
`
$("html, body").delay(500).animate({scrollTop: $("#divUnidades").offset().top}, 500);
`

3. The edit elements are inside a datatable:
![image](https://user-images.githubusercontent.com/21183018/31321038-704ecf56-ac44-11e7-83ac-54f383240530.png)
```

<tbody>
	<tr ng-repeat="row in allUnidades">
		<td style='text-align: center'>{{row.id.numeroUnidad}}</td>
		<td style='text-align: center'>{{row.numero}}</td>
		<td style='text-align: center'>{{row.torre}}</td>
		<td style='text-align: center'>{{row.piso}}</td>
		<td style='text-align: center'>{{row.nombreDetaInmueble}}</td>
		<td style='text-align: center; background-color: {{"#"+replace(row.colorEstadoInm)'>{{row.descripcionEstadoInm}}</td>
		<td style='text-align: center'>{{row.tarjeta}}</td>
		<td style='text-align: center'>{{row.claseDocumento +' '+row.identificacion +' '+ row.descripcionTercero}}</td>
		<td style='text-align: right'>{{row.valorTotal | number:2}}</td>
		<td style='text-align: right'>{{row.pagado | number:2}}</td>
		<td style='text-align: center'>
			<div ng-if="row.codigoEstadoInm == 'G' &amp;&amp; opt == 'V'">
				<a href="#"><i class="fa fa-ban fa-lg" aria-hidden="true"></i></a>&#160;
			</div>
			<div ng-if="row.codigoEstadoInm == 'G' &amp;&amp; opt == 'U'">
				<a href="#" ng-click="editRow(row)"><i class="fa fa-edit fa-lg" aria-hidden="true"></i></a>&#160;
			</div>
			<div ng-if="row.codigoEstadoInm != 'G'">
				<a href="#" ng-click="editRow(row)"><i class="fa fa-edit fa-lg" aria-hidden="true"></i></a>&#160;
			</div>
		</td>
	</tr>
</tbody>
```
The edit element is:
`<a href="#" ng-click="editRow(row)"><i class="fa fa-edit fa-lg" aria-hidden="true">`

4. The function editRow(row) opens the modal with this code (it's AngularJS):
```
$scope.editRow = function(data){
    $scope.edtUni = data;
    new jBox('Modal',{ 
        title: "..:: "+$scope.ppTitle+" ::..",
        content: $('#popEditUnidad'),
        blockScroll: false
    }).open();
}
```

In this point, I don't know if I'm doing something wrong...
I see your fiddle and it seems to work fine...
:(

Thanks again.

**Comment by StephanWagner** [comment]
Ah, I think I know whats scrolling to the top: <a href="#"></a>
Try <a href="javascript:;"></a>

**Comment by OswaldoMM** [comment]
Try... What... ?
:)

**Comment by StephanWagner** [comment]
This link here: 
`<a href="#" ng-click="editRow(row)"><i class="fa fa-edit fa-lg" aria-hidden="true">`

`href="#"` means that the document will scroll to an element which doesn't exist.

So you could either not use an `<a>` element:
`<span ng-click="editRow(row)"><i class="fa fa-edit fa-lg" aria-hidden="true">`

...or set the link to `href="javascript:;"` so it won't scroll when clicking on it:
`<a href="javascript:;" ng-click="editRow(row)"><i class="fa fa-edit fa-lg" aria-hidden="true">`

**Comment by OswaldoMM** [comment]
O_O'
You are a f****ing genius!!
It works!!!! It works!!!!
Thanks a lot!!!!!

**Comment by StephanWagner** [comment]
:) glad to help out.
Feel free to contact me if you run into any other trouble regarding jBox: hello@stephanwagner.me
Cheers!
