### ISSUE TITLE
forms in jbox won't submit on ios11

### ISSUE THREAD

**Issue by cgcullen** [StephanWagner/jBox#96]
I have a jbox popup with a small form. Works ok on desktop, but on ios11 safari, clicking the submit button just makes the jbox disappear without submitting the form.  Any ideas?

**Comment by StephanWagner** [comment]
Can you provide any code?
Or a fiddle... here is a blank one with jBox files you could fork: https://jsfiddle.net/StephanWagner/ov6d6960/

**Comment by cgcullen** [comment]
Stephan, I've added the code here.  I don't know enough about jsfiddle to add the ajax, but I put it in the html code so you could see what the ajax is returning.  https://jsfiddle.net/cindycullen/uqamj4L6/1/

IF we hit enter, the form submits, but clicking the submit button just makes the box disappear.  Again, this works fine on desktop and in previous versions of ios.

Thank you.

**Comment by StephanWagner** [comment]
Hmm, I can't reproduce the issue, just tested it with iPhone iOs 11 and the form seems to have submitted fine.

I noticed though that you create a new instance every tie you clock the n hold button. Check out this fiddle, thats how I'd do it:

https://jsfiddle.net/StephanWagner/ztxkuqw4/2/

You create one instance of jBox Modal and just reload the ajax once you click the on hold button.

**Comment by cgcullen** [comment]
Thank you Stephan!  I will try that out!
