### ISSUE TITLE
jBox cancellable option?

### ISSUE THREAD

**Issue by hkaraoglu** [StephanWagner/jBox#97]
Is there an option to cancel jBox popup when we touch outside of it?

**Comment by StephanWagner** [comment]
This should actually be the default setting. Although, it's not a tough event thats being triggered. jBox still uses click. Including touch events is still on the todo list, but I haven't gotten around improving jBox recently.

**Comment by StephanWagner** [comment]
Should be now fixed with v0.7.0.
